var holidays = {
   "2013" : {
      "apr" : {
         "1" : "Family Day",
         "27" : "Freedom Day"
      },
      "aug" : {
         "9" : "National Women's Day"
      },
      "dec" : {
         "16" : "Day of Reconciliation",
         "25" : "Christmas",
         "26" : "Day of Goodwill"
      },
      "jan" : {
         "1" : "New Year's Day"
      },
      "jun" : {
         "17" : "Youth Day (Soweto Day)"
      },
      "mar" : {
         "21" : "Human Rights Day",
         "29" : "Good Friday",
         "31" : "Easter Sunday"
      },
      "may" : {
         "1" : "Workers Day"
      },
      "sep" : {
         "24" : "Heritage Day"
      }
   },
   "2014" : {
      "apr" : {
         "18" : "Good Friday",
         "20" : "Easter Sunday",
         "21" : "Family Day",
         "28" : "Freedom Day"
      },
      "aug" : {
         "9" : "National Women's Day"
      },
      "dec" : {
         "16" : "Day of Reconciliation",
         "25" : "Christmas",
         "26" : "Day of Goodwill"
      },
      "jan" : {
         "1" : "New Year's Day"
      },
      "jun" : {
         "16" : "Youth Day (Soweto Day)"
      },
      "mar" : {
         "21" : "Human Rights Day"
      },
      "may" : {
         "1" : "Workers Day"
      },
      "sep" : {
         "24" : "Heritage Day"
      }
   },
   "2015" : {
      "apr" : {
         "27" : "Freedom Day",
         "3" : "Good Friday",
         "5" : "Easter Sunday",
         "6" : "Family Day"
      },
      "aug" : {
         "10" : "National Women's Day"
      },
      "dec" : {
         "16" : "Day of Reconciliation",
         "25" : "Christmas",
         "26" : "Day of Goodwill"
      },
      "jan" : {
         "1" : "New Year's Day"
      },
      "jun" : {
         "16" : "Youth Day (Soweto Day)"
      },
      "mar" : {
         "21" : "Human Rights Day"
      },
      "may" : {
         "1" : "Workers Day"
      },
      "sep" : {
         "24" : "Heritage Day"
      }
   },
   "2016" : {
      "apr" : {
         "27" : "Freedom Day"
      },
      "aug" : {
         "9" : "National Women's Day"
      },
      "dec" : {
         "16" : "Day of Reconciliation",
         "26" : "Christmas"
      },
      "jan" : {
         "1" : "New Year's Day"
      },
      "jun" : {
         "16" : "Youth Day (Soweto Day)"
      },
      "mar" : {
         "21" : "Human Rights Day",
         "25" : "Good Friday",
         "27" : "Easter Sunday",
         "28" : "Family Day"
      },
      "may" : {
         "2" : "Workers Day"
      },
      "sep" : {
         "24" : "Heritage Day"
      }
   },
   "2017" : {
      "apr" : {
         "14" : "Good Friday",
         "16" : "Easter Sunday",
         "17" : "Family Day",
         "27" : "Freedom Day"
      },
      "aug" : {
         "9" : "National Women's Day"
      },
      "dec" : {
         "16" : "Day of Reconciliation",
         "25" : "Christmas",
         "26" : "Day of Goodwill"
      },
      "jan" : {
         "2" : "New Year's Day"
      },
      "jun" : {
         "16" : "Youth Day (Soweto Day)"
      },
      "mar" : {
         "21" : "Human Rights Day"
      },
      "may" : {
         "1" : "Workers Day"
      },
      "sep" : {
         "25" : "Heritage Day"
      }
   },
   "2018" : {
      "apr" : {
         "1" : "Easter Sunday",
         "2" : "Family Day",
         "27" : "Freedom Day"
      },
      "aug" : {
         "9" : "National Women's Day"
      },
      "dec" : {
         "17" : "Day of Reconciliation",
         "25" : "Christmas",
         "26" : "Day of Goodwill"
      },
      "jan" : {
         "1" : "New Year's Day"
      },
      "jun" : {
         "16" : "Youth Day (Soweto Day)"
      },
      "mar" : {
         "21" : "Human Rights Day",
         "30" : "Good Friday"
      },
      "may" : {
         "1" : "Workers Day"
      },
      "sep" : {
         "24" : "Heritage Day"
      }
   }
};


var workdays = {
   "2013" : {
      "apr" : {
         "1" : "mon",
         "10" : "wed",
         "11" : "thu",
         "12" : "fri",
         "15" : "mon",
         "16" : "tue",
         "17" : "wed",
         "18" : "thu",
         "19" : "fri",
         "2" : "tue",
         "22" : "mon",
         "23" : "tue",
         "24" : "wed",
         "25" : "thu",
         "26" : "fri",
         "27" : "sat",
         "29" : "mon",
         "3" : "wed",
         "30" : "tue",
         "4" : "thu",
         "5" : "fri",
         "8" : "mon",
         "9" : "tue"
      },
      "aug" : {
         "1" : "thu",
         "12" : "mon",
         "13" : "tue",
         "14" : "wed",
         "15" : "thu",
         "16" : "fri",
         "19" : "mon",
         "2" : "fri",
         "20" : "tue",
         "21" : "wed",
         "22" : "thu",
         "23" : "fri",
         "26" : "mon",
         "27" : "tue",
         "28" : "wed",
         "29" : "thu",
         "30" : "fri",
         "5" : "mon",
         "6" : "tue",
         "7" : "wed",
         "8" : "thu",
         "9" : "fri"
      },
      "dec" : {
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "30" : "mon",
         "31" : "tue",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      },
      "feb" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri"
      },
      "jan" : {
         "1" : "tue",
         "10" : "thu",
         "11" : "fri",
         "14" : "mon",
         "15" : "tue",
         "16" : "wed",
         "17" : "thu",
         "18" : "fri",
         "2" : "wed",
         "21" : "mon",
         "22" : "tue",
         "23" : "wed",
         "24" : "thu",
         "25" : "fri",
         "28" : "mon",
         "29" : "tue",
         "3" : "thu",
         "30" : "wed",
         "31" : "thu",
         "4" : "fri",
         "7" : "mon",
         "8" : "tue",
         "9" : "wed"
      },
      "jul" : {
         "1" : "mon",
         "10" : "wed",
         "11" : "thu",
         "12" : "fri",
         "15" : "mon",
         "16" : "tue",
         "17" : "wed",
         "18" : "thu",
         "19" : "fri",
         "2" : "tue",
         "22" : "mon",
         "23" : "tue",
         "24" : "wed",
         "25" : "thu",
         "26" : "fri",
         "29" : "mon",
         "3" : "wed",
         "30" : "tue",
         "31" : "wed",
         "4" : "thu",
         "5" : "fri",
         "8" : "mon",
         "9" : "tue"
      },
      "jun" : {
         "10" : "mon",
         "11" : "tue",
         "12" : "wed",
         "13" : "thu",
         "14" : "fri",
         "17" : "mon",
         "18" : "tue",
         "19" : "wed",
         "20" : "thu",
         "21" : "fri",
         "24" : "mon",
         "25" : "tue",
         "26" : "wed",
         "27" : "thu",
         "28" : "fri",
         "3" : "mon",
         "4" : "tue",
         "5" : "wed",
         "6" : "thu",
         "7" : "fri"
      },
      "mar" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "29" : "fri",
         "31" : "sun",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri"
      },
      "may" : {
         "1" : "wed",
         "10" : "fri",
         "13" : "mon",
         "14" : "tue",
         "15" : "wed",
         "16" : "thu",
         "17" : "fri",
         "2" : "thu",
         "20" : "mon",
         "21" : "tue",
         "22" : "wed",
         "23" : "thu",
         "24" : "fri",
         "27" : "mon",
         "28" : "tue",
         "29" : "wed",
         "3" : "fri",
         "30" : "thu",
         "31" : "fri",
         "6" : "mon",
         "7" : "tue",
         "8" : "wed",
         "9" : "thu"
      },
      "nov" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "29" : "fri",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri"
      },
      "oct" : {
         "1" : "tue",
         "10" : "thu",
         "11" : "fri",
         "14" : "mon",
         "15" : "tue",
         "16" : "wed",
         "17" : "thu",
         "18" : "fri",
         "2" : "wed",
         "21" : "mon",
         "22" : "tue",
         "23" : "wed",
         "24" : "thu",
         "25" : "fri",
         "28" : "mon",
         "29" : "tue",
         "3" : "thu",
         "30" : "wed",
         "31" : "thu",
         "4" : "fri",
         "7" : "mon",
         "8" : "tue",
         "9" : "wed"
      },
      "sep" : {
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "30" : "mon",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      }
   },
   "2014" : {
      "apr" : {
         "1" : "tue",
         "10" : "thu",
         "11" : "fri",
         "14" : "mon",
         "15" : "tue",
         "16" : "wed",
         "17" : "thu",
         "18" : "fri",
         "2" : "wed",
         "20" : "sun",
         "21" : "mon",
         "22" : "tue",
         "23" : "wed",
         "24" : "thu",
         "25" : "fri",
         "28" : "mon",
         "29" : "tue",
         "3" : "thu",
         "30" : "wed",
         "4" : "fri",
         "7" : "mon",
         "8" : "tue",
         "9" : "wed"
      },
      "aug" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "29" : "fri",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri",
         "9" : "sat"
      },
      "dec" : {
         "1" : "mon",
         "10" : "wed",
         "11" : "thu",
         "12" : "fri",
         "15" : "mon",
         "16" : "tue",
         "17" : "wed",
         "18" : "thu",
         "19" : "fri",
         "2" : "tue",
         "22" : "mon",
         "23" : "tue",
         "24" : "wed",
         "25" : "thu",
         "26" : "fri",
         "29" : "mon",
         "3" : "wed",
         "30" : "tue",
         "31" : "wed",
         "4" : "thu",
         "5" : "fri",
         "8" : "mon",
         "9" : "tue"
      },
      "feb" : {
         "10" : "mon",
         "11" : "tue",
         "12" : "wed",
         "13" : "thu",
         "14" : "fri",
         "17" : "mon",
         "18" : "tue",
         "19" : "wed",
         "20" : "thu",
         "21" : "fri",
         "24" : "mon",
         "25" : "tue",
         "26" : "wed",
         "27" : "thu",
         "28" : "fri",
         "3" : "mon",
         "4" : "tue",
         "5" : "wed",
         "6" : "thu",
         "7" : "fri"
      },
      "jan" : {
         "1" : "wed",
         "10" : "fri",
         "13" : "mon",
         "14" : "tue",
         "15" : "wed",
         "16" : "thu",
         "17" : "fri",
         "2" : "thu",
         "20" : "mon",
         "21" : "tue",
         "22" : "wed",
         "23" : "thu",
         "24" : "fri",
         "27" : "mon",
         "28" : "tue",
         "29" : "wed",
         "3" : "fri",
         "30" : "thu",
         "31" : "fri",
         "6" : "mon",
         "7" : "tue",
         "8" : "wed",
         "9" : "thu"
      },
      "jul" : {
         "1" : "tue",
         "10" : "thu",
         "11" : "fri",
         "14" : "mon",
         "15" : "tue",
         "16" : "wed",
         "17" : "thu",
         "18" : "fri",
         "2" : "wed",
         "21" : "mon",
         "22" : "tue",
         "23" : "wed",
         "24" : "thu",
         "25" : "fri",
         "28" : "mon",
         "29" : "tue",
         "3" : "thu",
         "30" : "wed",
         "31" : "thu",
         "4" : "fri",
         "7" : "mon",
         "8" : "tue",
         "9" : "wed"
      },
      "jun" : {
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "30" : "mon",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      },
      "mar" : {
         "10" : "mon",
         "11" : "tue",
         "12" : "wed",
         "13" : "thu",
         "14" : "fri",
         "17" : "mon",
         "18" : "tue",
         "19" : "wed",
         "20" : "thu",
         "21" : "fri",
         "24" : "mon",
         "25" : "tue",
         "26" : "wed",
         "27" : "thu",
         "28" : "fri",
         "3" : "mon",
         "31" : "mon",
         "4" : "tue",
         "5" : "wed",
         "6" : "thu",
         "7" : "fri"
      },
      "may" : {
         "1" : "thu",
         "12" : "mon",
         "13" : "tue",
         "14" : "wed",
         "15" : "thu",
         "16" : "fri",
         "19" : "mon",
         "2" : "fri",
         "20" : "tue",
         "21" : "wed",
         "22" : "thu",
         "23" : "fri",
         "26" : "mon",
         "27" : "tue",
         "28" : "wed",
         "29" : "thu",
         "30" : "fri",
         "5" : "mon",
         "6" : "tue",
         "7" : "wed",
         "8" : "thu",
         "9" : "fri"
      },
      "nov" : {
         "10" : "mon",
         "11" : "tue",
         "12" : "wed",
         "13" : "thu",
         "14" : "fri",
         "17" : "mon",
         "18" : "tue",
         "19" : "wed",
         "20" : "thu",
         "21" : "fri",
         "24" : "mon",
         "25" : "tue",
         "26" : "wed",
         "27" : "thu",
         "28" : "fri",
         "3" : "mon",
         "4" : "tue",
         "5" : "wed",
         "6" : "thu",
         "7" : "fri"
      },
      "oct" : {
         "1" : "wed",
         "10" : "fri",
         "13" : "mon",
         "14" : "tue",
         "15" : "wed",
         "16" : "thu",
         "17" : "fri",
         "2" : "thu",
         "20" : "mon",
         "21" : "tue",
         "22" : "wed",
         "23" : "thu",
         "24" : "fri",
         "27" : "mon",
         "28" : "tue",
         "29" : "wed",
         "3" : "fri",
         "30" : "thu",
         "31" : "fri",
         "6" : "mon",
         "7" : "tue",
         "8" : "wed",
         "9" : "thu"
      },
      "sep" : {
         "1" : "mon",
         "10" : "wed",
         "11" : "thu",
         "12" : "fri",
         "15" : "mon",
         "16" : "tue",
         "17" : "wed",
         "18" : "thu",
         "19" : "fri",
         "2" : "tue",
         "22" : "mon",
         "23" : "tue",
         "24" : "wed",
         "25" : "thu",
         "26" : "fri",
         "29" : "mon",
         "3" : "wed",
         "30" : "tue",
         "4" : "thu",
         "5" : "fri",
         "8" : "mon",
         "9" : "tue"
      }
   },
   "2015" : {
      "apr" : {
         "1" : "wed",
         "10" : "fri",
         "13" : "mon",
         "14" : "tue",
         "15" : "wed",
         "16" : "thu",
         "17" : "fri",
         "2" : "thu",
         "20" : "mon",
         "21" : "tue",
         "22" : "wed",
         "23" : "thu",
         "24" : "fri",
         "27" : "mon",
         "28" : "tue",
         "29" : "wed",
         "3" : "fri",
         "30" : "thu",
         "5" : "sun",
         "6" : "mon",
         "7" : "tue",
         "8" : "wed",
         "9" : "thu"
      },
      "aug" : {
         "10" : "mon",
         "11" : "tue",
         "12" : "wed",
         "13" : "thu",
         "14" : "fri",
         "17" : "mon",
         "18" : "tue",
         "19" : "wed",
         "20" : "thu",
         "21" : "fri",
         "24" : "mon",
         "25" : "tue",
         "26" : "wed",
         "27" : "thu",
         "28" : "fri",
         "3" : "mon",
         "31" : "mon",
         "4" : "tue",
         "5" : "wed",
         "6" : "thu",
         "7" : "fri"
      },
      "dec" : {
         "1" : "tue",
         "10" : "thu",
         "11" : "fri",
         "14" : "mon",
         "15" : "tue",
         "16" : "wed",
         "17" : "thu",
         "18" : "fri",
         "2" : "wed",
         "21" : "mon",
         "22" : "tue",
         "23" : "wed",
         "24" : "thu",
         "25" : "fri",
         "26" : "sat",
         "28" : "mon",
         "29" : "tue",
         "3" : "thu",
         "30" : "wed",
         "31" : "thu",
         "4" : "fri",
         "7" : "mon",
         "8" : "tue",
         "9" : "wed"
      },
      "feb" : {
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      },
      "jan" : {
         "1" : "thu",
         "12" : "mon",
         "13" : "tue",
         "14" : "wed",
         "15" : "thu",
         "16" : "fri",
         "19" : "mon",
         "2" : "fri",
         "20" : "tue",
         "21" : "wed",
         "22" : "thu",
         "23" : "fri",
         "26" : "mon",
         "27" : "tue",
         "28" : "wed",
         "29" : "thu",
         "30" : "fri",
         "5" : "mon",
         "6" : "tue",
         "7" : "wed",
         "8" : "thu",
         "9" : "fri"
      },
      "jul" : {
         "1" : "wed",
         "10" : "fri",
         "13" : "mon",
         "14" : "tue",
         "15" : "wed",
         "16" : "thu",
         "17" : "fri",
         "2" : "thu",
         "20" : "mon",
         "21" : "tue",
         "22" : "wed",
         "23" : "thu",
         "24" : "fri",
         "27" : "mon",
         "28" : "tue",
         "29" : "wed",
         "3" : "fri",
         "30" : "thu",
         "31" : "fri",
         "6" : "mon",
         "7" : "tue",
         "8" : "wed",
         "9" : "thu"
      },
      "jun" : {
         "1" : "mon",
         "10" : "wed",
         "11" : "thu",
         "12" : "fri",
         "15" : "mon",
         "16" : "tue",
         "17" : "wed",
         "18" : "thu",
         "19" : "fri",
         "2" : "tue",
         "22" : "mon",
         "23" : "tue",
         "24" : "wed",
         "25" : "thu",
         "26" : "fri",
         "29" : "mon",
         "3" : "wed",
         "30" : "tue",
         "4" : "thu",
         "5" : "fri",
         "8" : "mon",
         "9" : "tue"
      },
      "mar" : {
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "21" : "sat",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "30" : "mon",
         "31" : "tue",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      },
      "may" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "29" : "fri",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri"
      },
      "nov" : {
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "30" : "mon",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      },
      "oct" : {
         "1" : "thu",
         "12" : "mon",
         "13" : "tue",
         "14" : "wed",
         "15" : "thu",
         "16" : "fri",
         "19" : "mon",
         "2" : "fri",
         "20" : "tue",
         "21" : "wed",
         "22" : "thu",
         "23" : "fri",
         "26" : "mon",
         "27" : "tue",
         "28" : "wed",
         "29" : "thu",
         "30" : "fri",
         "5" : "mon",
         "6" : "tue",
         "7" : "wed",
         "8" : "thu",
         "9" : "fri"
      },
      "sep" : {
         "1" : "tue",
         "10" : "thu",
         "11" : "fri",
         "14" : "mon",
         "15" : "tue",
         "16" : "wed",
         "17" : "thu",
         "18" : "fri",
         "2" : "wed",
         "21" : "mon",
         "22" : "tue",
         "23" : "wed",
         "24" : "thu",
         "25" : "fri",
         "28" : "mon",
         "29" : "tue",
         "3" : "thu",
         "30" : "wed",
         "4" : "fri",
         "7" : "mon",
         "8" : "tue",
         "9" : "wed"
      }
   },
   "2016" : {
      "apr" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "29" : "fri",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri"
      },
      "aug" : {
         "1" : "mon",
         "10" : "wed",
         "11" : "thu",
         "12" : "fri",
         "15" : "mon",
         "16" : "tue",
         "17" : "wed",
         "18" : "thu",
         "19" : "fri",
         "2" : "tue",
         "22" : "mon",
         "23" : "tue",
         "24" : "wed",
         "25" : "thu",
         "26" : "fri",
         "29" : "mon",
         "3" : "wed",
         "30" : "tue",
         "31" : "wed",
         "4" : "thu",
         "5" : "fri",
         "8" : "mon",
         "9" : "tue"
      },
      "dec" : {
         "1" : "thu",
         "12" : "mon",
         "13" : "tue",
         "14" : "wed",
         "15" : "thu",
         "16" : "fri",
         "19" : "mon",
         "2" : "fri",
         "20" : "tue",
         "21" : "wed",
         "22" : "thu",
         "23" : "fri",
         "26" : "mon",
         "27" : "tue",
         "28" : "wed",
         "29" : "thu",
         "30" : "fri",
         "5" : "mon",
         "6" : "tue",
         "7" : "wed",
         "8" : "thu",
         "9" : "fri"
      },
      "feb" : {
         "1" : "mon",
         "10" : "wed",
         "11" : "thu",
         "12" : "fri",
         "15" : "mon",
         "16" : "tue",
         "17" : "wed",
         "18" : "thu",
         "19" : "fri",
         "2" : "tue",
         "22" : "mon",
         "23" : "tue",
         "24" : "wed",
         "25" : "thu",
         "26" : "fri",
         "29" : "mon",
         "3" : "wed",
         "4" : "thu",
         "5" : "fri",
         "8" : "mon",
         "9" : "tue"
      },
      "jan" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "29" : "fri",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri"
      },
      "jul" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "29" : "fri",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri"
      },
      "jun" : {
         "1" : "wed",
         "10" : "fri",
         "13" : "mon",
         "14" : "tue",
         "15" : "wed",
         "16" : "thu",
         "17" : "fri",
         "2" : "thu",
         "20" : "mon",
         "21" : "tue",
         "22" : "wed",
         "23" : "thu",
         "24" : "fri",
         "27" : "mon",
         "28" : "tue",
         "29" : "wed",
         "3" : "fri",
         "30" : "thu",
         "6" : "mon",
         "7" : "tue",
         "8" : "wed",
         "9" : "thu"
      },
      "mar" : {
         "1" : "tue",
         "10" : "thu",
         "11" : "fri",
         "14" : "mon",
         "15" : "tue",
         "16" : "wed",
         "17" : "thu",
         "18" : "fri",
         "2" : "wed",
         "21" : "mon",
         "22" : "tue",
         "23" : "wed",
         "24" : "thu",
         "25" : "fri",
         "27" : "sun",
         "28" : "mon",
         "29" : "tue",
         "3" : "thu",
         "30" : "wed",
         "31" : "thu",
         "4" : "fri",
         "7" : "mon",
         "8" : "tue",
         "9" : "wed"
      },
      "may" : {
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "30" : "mon",
         "31" : "tue",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      },
      "nov" : {
         "1" : "tue",
         "10" : "thu",
         "11" : "fri",
         "14" : "mon",
         "15" : "tue",
         "16" : "wed",
         "17" : "thu",
         "18" : "fri",
         "2" : "wed",
         "21" : "mon",
         "22" : "tue",
         "23" : "wed",
         "24" : "thu",
         "25" : "fri",
         "28" : "mon",
         "29" : "tue",
         "3" : "thu",
         "30" : "wed",
         "4" : "fri",
         "7" : "mon",
         "8" : "tue",
         "9" : "wed"
      },
      "oct" : {
         "10" : "mon",
         "11" : "tue",
         "12" : "wed",
         "13" : "thu",
         "14" : "fri",
         "17" : "mon",
         "18" : "tue",
         "19" : "wed",
         "20" : "thu",
         "21" : "fri",
         "24" : "mon",
         "25" : "tue",
         "26" : "wed",
         "27" : "thu",
         "28" : "fri",
         "3" : "mon",
         "31" : "mon",
         "4" : "tue",
         "5" : "wed",
         "6" : "thu",
         "7" : "fri"
      },
      "sep" : {
         "1" : "thu",
         "12" : "mon",
         "13" : "tue",
         "14" : "wed",
         "15" : "thu",
         "16" : "fri",
         "19" : "mon",
         "2" : "fri",
         "20" : "tue",
         "21" : "wed",
         "22" : "thu",
         "23" : "fri",
         "24" : "sat",
         "26" : "mon",
         "27" : "tue",
         "28" : "wed",
         "29" : "thu",
         "30" : "fri",
         "5" : "mon",
         "6" : "tue",
         "7" : "wed",
         "8" : "thu",
         "9" : "fri"
      }
   },
   "2017" : {
      "apr" : {
         "10" : "mon",
         "11" : "tue",
         "12" : "wed",
         "13" : "thu",
         "14" : "fri",
         "16" : "sun",
         "17" : "mon",
         "18" : "tue",
         "19" : "wed",
         "20" : "thu",
         "21" : "fri",
         "24" : "mon",
         "25" : "tue",
         "26" : "wed",
         "27" : "thu",
         "28" : "fri",
         "3" : "mon",
         "4" : "tue",
         "5" : "wed",
         "6" : "thu",
         "7" : "fri"
      },
      "aug" : {
         "1" : "tue",
         "10" : "thu",
         "11" : "fri",
         "14" : "mon",
         "15" : "tue",
         "16" : "wed",
         "17" : "thu",
         "18" : "fri",
         "2" : "wed",
         "21" : "mon",
         "22" : "tue",
         "23" : "wed",
         "24" : "thu",
         "25" : "fri",
         "28" : "mon",
         "29" : "tue",
         "3" : "thu",
         "30" : "wed",
         "31" : "thu",
         "4" : "fri",
         "7" : "mon",
         "8" : "tue",
         "9" : "wed"
      },
      "dec" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "16" : "sat",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "29" : "fri",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri"
      },
      "feb" : {
         "1" : "wed",
         "10" : "fri",
         "13" : "mon",
         "14" : "tue",
         "15" : "wed",
         "16" : "thu",
         "17" : "fri",
         "2" : "thu",
         "20" : "mon",
         "21" : "tue",
         "22" : "wed",
         "23" : "thu",
         "24" : "fri",
         "27" : "mon",
         "28" : "tue",
         "3" : "fri",
         "6" : "mon",
         "7" : "tue",
         "8" : "wed",
         "9" : "thu"
      },
      "jan" : {
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "30" : "mon",
         "31" : "tue",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      },
      "jul" : {
         "10" : "mon",
         "11" : "tue",
         "12" : "wed",
         "13" : "thu",
         "14" : "fri",
         "17" : "mon",
         "18" : "tue",
         "19" : "wed",
         "20" : "thu",
         "21" : "fri",
         "24" : "mon",
         "25" : "tue",
         "26" : "wed",
         "27" : "thu",
         "28" : "fri",
         "3" : "mon",
         "31" : "mon",
         "4" : "tue",
         "5" : "wed",
         "6" : "thu",
         "7" : "fri"
      },
      "jun" : {
         "1" : "thu",
         "12" : "mon",
         "13" : "tue",
         "14" : "wed",
         "15" : "thu",
         "16" : "fri",
         "19" : "mon",
         "2" : "fri",
         "20" : "tue",
         "21" : "wed",
         "22" : "thu",
         "23" : "fri",
         "26" : "mon",
         "27" : "tue",
         "28" : "wed",
         "29" : "thu",
         "30" : "fri",
         "5" : "mon",
         "6" : "tue",
         "7" : "wed",
         "8" : "thu",
         "9" : "fri"
      },
      "mar" : {
         "1" : "wed",
         "10" : "fri",
         "13" : "mon",
         "14" : "tue",
         "15" : "wed",
         "16" : "thu",
         "17" : "fri",
         "2" : "thu",
         "20" : "mon",
         "21" : "tue",
         "22" : "wed",
         "23" : "thu",
         "24" : "fri",
         "27" : "mon",
         "28" : "tue",
         "29" : "wed",
         "3" : "fri",
         "30" : "thu",
         "31" : "fri",
         "6" : "mon",
         "7" : "tue",
         "8" : "wed",
         "9" : "thu"
      },
      "may" : {
         "1" : "mon",
         "10" : "wed",
         "11" : "thu",
         "12" : "fri",
         "15" : "mon",
         "16" : "tue",
         "17" : "wed",
         "18" : "thu",
         "19" : "fri",
         "2" : "tue",
         "22" : "mon",
         "23" : "tue",
         "24" : "wed",
         "25" : "thu",
         "26" : "fri",
         "29" : "mon",
         "3" : "wed",
         "30" : "tue",
         "31" : "wed",
         "4" : "thu",
         "5" : "fri",
         "8" : "mon",
         "9" : "tue"
      },
      "nov" : {
         "1" : "wed",
         "10" : "fri",
         "13" : "mon",
         "14" : "tue",
         "15" : "wed",
         "16" : "thu",
         "17" : "fri",
         "2" : "thu",
         "20" : "mon",
         "21" : "tue",
         "22" : "wed",
         "23" : "thu",
         "24" : "fri",
         "27" : "mon",
         "28" : "tue",
         "29" : "wed",
         "3" : "fri",
         "30" : "thu",
         "6" : "mon",
         "7" : "tue",
         "8" : "wed",
         "9" : "thu"
      },
      "oct" : {
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "30" : "mon",
         "31" : "tue",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      },
      "sep" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "29" : "fri",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri"
      }
   },
   "2018" : {
      "apr" : {
         "1" : "sun",
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "30" : "mon",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      },
      "aug" : {
         "1" : "wed",
         "10" : "fri",
         "13" : "mon",
         "14" : "tue",
         "15" : "wed",
         "16" : "thu",
         "17" : "fri",
         "2" : "thu",
         "20" : "mon",
         "21" : "tue",
         "22" : "wed",
         "23" : "thu",
         "24" : "fri",
         "27" : "mon",
         "28" : "tue",
         "29" : "wed",
         "3" : "fri",
         "30" : "thu",
         "31" : "fri",
         "6" : "mon",
         "7" : "tue",
         "8" : "wed",
         "9" : "thu"
      },
      "dec" : {
         "10" : "mon",
         "11" : "tue",
         "12" : "wed",
         "13" : "thu",
         "14" : "fri",
         "17" : "mon",
         "18" : "tue",
         "19" : "wed",
         "20" : "thu",
         "21" : "fri",
         "24" : "mon",
         "25" : "tue",
         "26" : "wed",
         "27" : "thu",
         "28" : "fri",
         "3" : "mon",
         "31" : "mon",
         "4" : "tue",
         "5" : "wed",
         "6" : "thu",
         "7" : "fri"
      },
      "feb" : {
         "1" : "thu",
         "12" : "mon",
         "13" : "tue",
         "14" : "wed",
         "15" : "thu",
         "16" : "fri",
         "19" : "mon",
         "2" : "fri",
         "20" : "tue",
         "21" : "wed",
         "22" : "thu",
         "23" : "fri",
         "26" : "mon",
         "27" : "tue",
         "28" : "wed",
         "5" : "mon",
         "6" : "tue",
         "7" : "wed",
         "8" : "thu",
         "9" : "fri"
      },
      "jan" : {
         "1" : "mon",
         "10" : "wed",
         "11" : "thu",
         "12" : "fri",
         "15" : "mon",
         "16" : "tue",
         "17" : "wed",
         "18" : "thu",
         "19" : "fri",
         "2" : "tue",
         "22" : "mon",
         "23" : "tue",
         "24" : "wed",
         "25" : "thu",
         "26" : "fri",
         "29" : "mon",
         "3" : "wed",
         "30" : "tue",
         "31" : "wed",
         "4" : "thu",
         "5" : "fri",
         "8" : "mon",
         "9" : "tue"
      },
      "jul" : {
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "30" : "mon",
         "31" : "tue",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      },
      "jun" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "16" : "sat",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "29" : "fri",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri"
      },
      "mar" : {
         "1" : "thu",
         "12" : "mon",
         "13" : "tue",
         "14" : "wed",
         "15" : "thu",
         "16" : "fri",
         "19" : "mon",
         "2" : "fri",
         "20" : "tue",
         "21" : "wed",
         "22" : "thu",
         "23" : "fri",
         "26" : "mon",
         "27" : "tue",
         "28" : "wed",
         "29" : "thu",
         "30" : "fri",
         "5" : "mon",
         "6" : "tue",
         "7" : "wed",
         "8" : "thu",
         "9" : "fri"
      },
      "may" : {
         "1" : "tue",
         "10" : "thu",
         "11" : "fri",
         "14" : "mon",
         "15" : "tue",
         "16" : "wed",
         "17" : "thu",
         "18" : "fri",
         "2" : "wed",
         "21" : "mon",
         "22" : "tue",
         "23" : "wed",
         "24" : "thu",
         "25" : "fri",
         "28" : "mon",
         "29" : "tue",
         "3" : "thu",
         "30" : "wed",
         "31" : "thu",
         "4" : "fri",
         "7" : "mon",
         "8" : "tue",
         "9" : "wed"
      },
      "nov" : {
         "1" : "thu",
         "12" : "mon",
         "13" : "tue",
         "14" : "wed",
         "15" : "thu",
         "16" : "fri",
         "19" : "mon",
         "2" : "fri",
         "20" : "tue",
         "21" : "wed",
         "22" : "thu",
         "23" : "fri",
         "26" : "mon",
         "27" : "tue",
         "28" : "wed",
         "29" : "thu",
         "30" : "fri",
         "5" : "mon",
         "6" : "tue",
         "7" : "wed",
         "8" : "thu",
         "9" : "fri"
      },
      "oct" : {
         "1" : "mon",
         "10" : "wed",
         "11" : "thu",
         "12" : "fri",
         "15" : "mon",
         "16" : "tue",
         "17" : "wed",
         "18" : "thu",
         "19" : "fri",
         "2" : "tue",
         "22" : "mon",
         "23" : "tue",
         "24" : "wed",
         "25" : "thu",
         "26" : "fri",
         "29" : "mon",
         "3" : "wed",
         "30" : "tue",
         "31" : "wed",
         "4" : "thu",
         "5" : "fri",
         "8" : "mon",
         "9" : "tue"
      },
      "sep" : {
         "10" : "mon",
         "11" : "tue",
         "12" : "wed",
         "13" : "thu",
         "14" : "fri",
         "17" : "mon",
         "18" : "tue",
         "19" : "wed",
         "20" : "thu",
         "21" : "fri",
         "24" : "mon",
         "25" : "tue",
         "26" : "wed",
         "27" : "thu",
         "28" : "fri",
         "3" : "mon",
         "4" : "tue",
         "5" : "wed",
         "6" : "thu",
         "7" : "fri"
      }
   }
};


