var holidays = {
   "2013" : {
      "Apr" : {
         "1" : "Family Day",
         "27" : "Freedom Day"
      },
      "Aug" : {
         "9" : "National Women's Day"
      },
      "Dec" : {
         "16" : "Day of Reconciliation",
         "25" : "Christmas",
         "26" : "Day of Goodwill"
      },
      "Jan" : {
         "1" : "New Year's Day"
      },
      "Jun" : {
         "17" : "Youth Day (Soweto Day)"
      },
      "Mar" : {
         "21" : "Human Rights Day",
         "29" : "Good Friday",
         "31" : "Easter Sunday"
      },
      "May" : {
         "1" : "Workers Day"
      },
      "Sep" : {
         "24" : "Heritage Day"
      }
   },
   "2014" : {
      "Apr" : {
         "18" : "Good Friday",
         "20" : "Easter Sunday",
         "21" : "Family Day",
         "28" : "Freedom Day"
      },
      "Aug" : {
         "9" : "National Women's Day"
      },
      "Dec" : {
         "16" : "Day of Reconciliation",
         "25" : "Christmas",
         "26" : "Day of Goodwill"
      },
      "Jan" : {
         "1" : "New Year's Day"
      },
      "Jun" : {
         "16" : "Youth Day (Soweto Day)"
      },
      "Mar" : {
         "21" : "Human Rights Day"
      },
      "May" : {
         "1" : "Workers Day"
      },
      "Sep" : {
         "24" : "Heritage Day"
      }
   },
   "2015" : {
      "Apr" : {
         "27" : "Freedom Day",
         "3" : "Good Friday",
         "5" : "Easter Sunday",
         "6" : "Family Day"
      },
      "Aug" : {
         "10" : "National Women's Day"
      },
      "Dec" : {
         "16" : "Day of Reconciliation",
         "25" : "Christmas",
         "26" : "Day of Goodwill"
      },
      "Jan" : {
         "1" : "New Year's Day"
      },
      "Jun" : {
         "16" : "Youth Day (Soweto Day)"
      },
      "Mar" : {
         "21" : "Human Rights Day"
      },
      "May" : {
         "1" : "Workers Day"
      },
      "Sep" : {
         "24" : "Heritage Day"
      }
   },
   "2016" : {
      "Apr" : {
         "27" : "Freedom Day"
      },
      "Aug" : {
         "9" : "National Women's Day"
      },
      "Dec" : {
         "16" : "Day of Reconciliation",
         "26" : "Christmas"
      },
      "Jan" : {
         "1" : "New Year's Day"
      },
      "Jun" : {
         "16" : "Youth Day (Soweto Day)"
      },
      "Mar" : {
         "21" : "Human Rights Day",
         "25" : "Good Friday",
         "27" : "Easter Sunday",
         "28" : "Family Day"
      },
      "May" : {
         "2" : "Workers Day"
      },
      "Sep" : {
         "24" : "Heritage Day"
      }
   },
   "2017" : {
      "Apr" : {
         "14" : "Good Friday",
         "16" : "Easter Sunday",
         "17" : "Family Day",
         "27" : "Freedom Day"
      },
      "Aug" : {
         "9" : "National Women's Day"
      },
      "Dec" : {
         "16" : "Day of Reconciliation",
         "25" : "Christmas",
         "26" : "Day of Goodwill"
      },
      "Jan" : {
         "2" : "New Year's Day"
      },
      "Jun" : {
         "16" : "Youth Day (Soweto Day)"
      },
      "Mar" : {
         "21" : "Human Rights Day"
      },
      "May" : {
         "1" : "Workers Day"
      },
      "Sep" : {
         "25" : "Heritage Day"
      }
   },
   "2018" : {
      "Apr" : {
         "1" : "Easter Sunday",
         "2" : "Family Day",
         "27" : "Freedom Day"
      },
      "Aug" : {
         "9" : "National Women's Day"
      },
      "Dec" : {
         "17" : "Day of Reconciliation",
         "25" : "Christmas",
         "26" : "Day of Goodwill"
      },
      "Jan" : {
         "1" : "New Year's Day"
      },
      "Jun" : {
         "16" : "Youth Day (Soweto Day)"
      },
      "Mar" : {
         "21" : "Human Rights Day",
         "30" : "Good Friday"
      },
      "May" : {
         "1" : "Workers Day"
      },
      "Sep" : {
         "24" : "Heritage Day"
      }
   }
};

var workdays = {
   "2013" : {
      "Apr" : {
         "1" : "mon",
         "10" : "wed",
         "11" : "thu",
         "12" : "fri",
         "15" : "mon",
         "16" : "tue",
         "17" : "wed",
         "18" : "thu",
         "19" : "fri",
         "2" : "tue",
         "22" : "mon",
         "23" : "tue",
         "24" : "wed",
         "25" : "thu",
         "26" : "fri",
         "27" : "sat",
         "29" : "mon",
         "3" : "wed",
         "30" : "tue",
         "4" : "thu",
         "5" : "fri",
         "8" : "mon",
         "9" : "tue"
      },
      "Aug" : {
         "1" : "thu",
         "12" : "mon",
         "13" : "tue",
         "14" : "wed",
         "15" : "thu",
         "16" : "fri",
         "19" : "mon",
         "2" : "fri",
         "20" : "tue",
         "21" : "wed",
         "22" : "thu",
         "23" : "fri",
         "26" : "mon",
         "27" : "tue",
         "28" : "wed",
         "29" : "thu",
         "30" : "fri",
         "5" : "mon",
         "6" : "tue",
         "7" : "wed",
         "8" : "thu",
         "9" : "fri"
      },
      "Dec" : {
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "30" : "mon",
         "31" : "tue",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      },
      "Feb" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri"
      },
      "Jan" : {
         "1" : "tue",
         "10" : "thu",
         "11" : "fri",
         "14" : "mon",
         "15" : "tue",
         "16" : "wed",
         "17" : "thu",
         "18" : "fri",
         "2" : "wed",
         "21" : "mon",
         "22" : "tue",
         "23" : "wed",
         "24" : "thu",
         "25" : "fri",
         "28" : "mon",
         "29" : "tue",
         "3" : "thu",
         "30" : "wed",
         "31" : "thu",
         "4" : "fri",
         "7" : "mon",
         "8" : "tue",
         "9" : "wed"
      },
      "Jul" : {
         "1" : "mon",
         "10" : "wed",
         "11" : "thu",
         "12" : "fri",
         "15" : "mon",
         "16" : "tue",
         "17" : "wed",
         "18" : "thu",
         "19" : "fri",
         "2" : "tue",
         "22" : "mon",
         "23" : "tue",
         "24" : "wed",
         "25" : "thu",
         "26" : "fri",
         "29" : "mon",
         "3" : "wed",
         "30" : "tue",
         "31" : "wed",
         "4" : "thu",
         "5" : "fri",
         "8" : "mon",
         "9" : "tue"
      },
      "Jun" : {
         "10" : "mon",
         "11" : "tue",
         "12" : "wed",
         "13" : "thu",
         "14" : "fri",
         "17" : "mon",
         "18" : "tue",
         "19" : "wed",
         "20" : "thu",
         "21" : "fri",
         "24" : "mon",
         "25" : "tue",
         "26" : "wed",
         "27" : "thu",
         "28" : "fri",
         "3" : "mon",
         "4" : "tue",
         "5" : "wed",
         "6" : "thu",
         "7" : "fri"
      },
      "Mar" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "29" : "fri",
         "31" : "sun",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri"
      },
      "May" : {
         "1" : "wed",
         "10" : "fri",
         "13" : "mon",
         "14" : "tue",
         "15" : "wed",
         "16" : "thu",
         "17" : "fri",
         "2" : "thu",
         "20" : "mon",
         "21" : "tue",
         "22" : "wed",
         "23" : "thu",
         "24" : "fri",
         "27" : "mon",
         "28" : "tue",
         "29" : "wed",
         "3" : "fri",
         "30" : "thu",
         "31" : "fri",
         "6" : "mon",
         "7" : "tue",
         "8" : "wed",
         "9" : "thu"
      },
      "Nov" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "29" : "fri",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri"
      },
      "Oct" : {
         "1" : "tue",
         "10" : "thu",
         "11" : "fri",
         "14" : "mon",
         "15" : "tue",
         "16" : "wed",
         "17" : "thu",
         "18" : "fri",
         "2" : "wed",
         "21" : "mon",
         "22" : "tue",
         "23" : "wed",
         "24" : "thu",
         "25" : "fri",
         "28" : "mon",
         "29" : "tue",
         "3" : "thu",
         "30" : "wed",
         "31" : "thu",
         "4" : "fri",
         "7" : "mon",
         "8" : "tue",
         "9" : "wed"
      },
      "Sep" : {
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "30" : "mon",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      }
   },
   "2014" : {
      "Apr" : {
         "1" : "tue",
         "10" : "thu",
         "11" : "fri",
         "14" : "mon",
         "15" : "tue",
         "16" : "wed",
         "17" : "thu",
         "18" : "fri",
         "2" : "wed",
         "20" : "sun",
         "21" : "mon",
         "22" : "tue",
         "23" : "wed",
         "24" : "thu",
         "25" : "fri",
         "28" : "mon",
         "29" : "tue",
         "3" : "thu",
         "30" : "wed",
         "4" : "fri",
         "7" : "mon",
         "8" : "tue",
         "9" : "wed"
      },
      "Aug" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "29" : "fri",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri",
         "9" : "sat"
      },
      "Dec" : {
         "1" : "mon",
         "10" : "wed",
         "11" : "thu",
         "12" : "fri",
         "15" : "mon",
         "16" : "tue",
         "17" : "wed",
         "18" : "thu",
         "19" : "fri",
         "2" : "tue",
         "22" : "mon",
         "23" : "tue",
         "24" : "wed",
         "25" : "thu",
         "26" : "fri",
         "29" : "mon",
         "3" : "wed",
         "30" : "tue",
         "31" : "wed",
         "4" : "thu",
         "5" : "fri",
         "8" : "mon",
         "9" : "tue"
      },
      "Feb" : {
         "10" : "mon",
         "11" : "tue",
         "12" : "wed",
         "13" : "thu",
         "14" : "fri",
         "17" : "mon",
         "18" : "tue",
         "19" : "wed",
         "20" : "thu",
         "21" : "fri",
         "24" : "mon",
         "25" : "tue",
         "26" : "wed",
         "27" : "thu",
         "28" : "fri",
         "3" : "mon",
         "4" : "tue",
         "5" : "wed",
         "6" : "thu",
         "7" : "fri"
      },
      "Jan" : {
         "1" : "wed",
         "10" : "fri",
         "13" : "mon",
         "14" : "tue",
         "15" : "wed",
         "16" : "thu",
         "17" : "fri",
         "2" : "thu",
         "20" : "mon",
         "21" : "tue",
         "22" : "wed",
         "23" : "thu",
         "24" : "fri",
         "27" : "mon",
         "28" : "tue",
         "29" : "wed",
         "3" : "fri",
         "30" : "thu",
         "31" : "fri",
         "6" : "mon",
         "7" : "tue",
         "8" : "wed",
         "9" : "thu"
      },
      "Jul" : {
         "1" : "tue",
         "10" : "thu",
         "11" : "fri",
         "14" : "mon",
         "15" : "tue",
         "16" : "wed",
         "17" : "thu",
         "18" : "fri",
         "2" : "wed",
         "21" : "mon",
         "22" : "tue",
         "23" : "wed",
         "24" : "thu",
         "25" : "fri",
         "28" : "mon",
         "29" : "tue",
         "3" : "thu",
         "30" : "wed",
         "31" : "thu",
         "4" : "fri",
         "7" : "mon",
         "8" : "tue",
         "9" : "wed"
      },
      "Jun" : {
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "30" : "mon",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      },
      "Mar" : {
         "10" : "mon",
         "11" : "tue",
         "12" : "wed",
         "13" : "thu",
         "14" : "fri",
         "17" : "mon",
         "18" : "tue",
         "19" : "wed",
         "20" : "thu",
         "21" : "fri",
         "24" : "mon",
         "25" : "tue",
         "26" : "wed",
         "27" : "thu",
         "28" : "fri",
         "3" : "mon",
         "31" : "mon",
         "4" : "tue",
         "5" : "wed",
         "6" : "thu",
         "7" : "fri"
      },
      "May" : {
         "1" : "thu",
         "12" : "mon",
         "13" : "tue",
         "14" : "wed",
         "15" : "thu",
         "16" : "fri",
         "19" : "mon",
         "2" : "fri",
         "20" : "tue",
         "21" : "wed",
         "22" : "thu",
         "23" : "fri",
         "26" : "mon",
         "27" : "tue",
         "28" : "wed",
         "29" : "thu",
         "30" : "fri",
         "5" : "mon",
         "6" : "tue",
         "7" : "wed",
         "8" : "thu",
         "9" : "fri"
      },
      "Nov" : {
         "10" : "mon",
         "11" : "tue",
         "12" : "wed",
         "13" : "thu",
         "14" : "fri",
         "17" : "mon",
         "18" : "tue",
         "19" : "wed",
         "20" : "thu",
         "21" : "fri",
         "24" : "mon",
         "25" : "tue",
         "26" : "wed",
         "27" : "thu",
         "28" : "fri",
         "3" : "mon",
         "4" : "tue",
         "5" : "wed",
         "6" : "thu",
         "7" : "fri"
      },
      "Oct" : {
         "1" : "wed",
         "10" : "fri",
         "13" : "mon",
         "14" : "tue",
         "15" : "wed",
         "16" : "thu",
         "17" : "fri",
         "2" : "thu",
         "20" : "mon",
         "21" : "tue",
         "22" : "wed",
         "23" : "thu",
         "24" : "fri",
         "27" : "mon",
         "28" : "tue",
         "29" : "wed",
         "3" : "fri",
         "30" : "thu",
         "31" : "fri",
         "6" : "mon",
         "7" : "tue",
         "8" : "wed",
         "9" : "thu"
      },
      "Sep" : {
         "1" : "mon",
         "10" : "wed",
         "11" : "thu",
         "12" : "fri",
         "15" : "mon",
         "16" : "tue",
         "17" : "wed",
         "18" : "thu",
         "19" : "fri",
         "2" : "tue",
         "22" : "mon",
         "23" : "tue",
         "24" : "wed",
         "25" : "thu",
         "26" : "fri",
         "29" : "mon",
         "3" : "wed",
         "30" : "tue",
         "4" : "thu",
         "5" : "fri",
         "8" : "mon",
         "9" : "tue"
      }
   },
   "2015" : {
      "Apr" : {
         "1" : "wed",
         "10" : "fri",
         "13" : "mon",
         "14" : "tue",
         "15" : "wed",
         "16" : "thu",
         "17" : "fri",
         "2" : "thu",
         "20" : "mon",
         "21" : "tue",
         "22" : "wed",
         "23" : "thu",
         "24" : "fri",
         "27" : "mon",
         "28" : "tue",
         "29" : "wed",
         "3" : "fri",
         "30" : "thu",
         "5" : "sun",
         "6" : "mon",
         "7" : "tue",
         "8" : "wed",
         "9" : "thu"
      },
      "Aug" : {
         "10" : "mon",
         "11" : "tue",
         "12" : "wed",
         "13" : "thu",
         "14" : "fri",
         "17" : "mon",
         "18" : "tue",
         "19" : "wed",
         "20" : "thu",
         "21" : "fri",
         "24" : "mon",
         "25" : "tue",
         "26" : "wed",
         "27" : "thu",
         "28" : "fri",
         "3" : "mon",
         "31" : "mon",
         "4" : "tue",
         "5" : "wed",
         "6" : "thu",
         "7" : "fri"
      },
      "Dec" : {
         "1" : "tue",
         "10" : "thu",
         "11" : "fri",
         "14" : "mon",
         "15" : "tue",
         "16" : "wed",
         "17" : "thu",
         "18" : "fri",
         "2" : "wed",
         "21" : "mon",
         "22" : "tue",
         "23" : "wed",
         "24" : "thu",
         "25" : "fri",
         "26" : "sat",
         "28" : "mon",
         "29" : "tue",
         "3" : "thu",
         "30" : "wed",
         "31" : "thu",
         "4" : "fri",
         "7" : "mon",
         "8" : "tue",
         "9" : "wed"
      },
      "Feb" : {
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      },
      "Jan" : {
         "1" : "thu",
         "12" : "mon",
         "13" : "tue",
         "14" : "wed",
         "15" : "thu",
         "16" : "fri",
         "19" : "mon",
         "2" : "fri",
         "20" : "tue",
         "21" : "wed",
         "22" : "thu",
         "23" : "fri",
         "26" : "mon",
         "27" : "tue",
         "28" : "wed",
         "29" : "thu",
         "30" : "fri",
         "5" : "mon",
         "6" : "tue",
         "7" : "wed",
         "8" : "thu",
         "9" : "fri"
      },
      "Jul" : {
         "1" : "wed",
         "10" : "fri",
         "13" : "mon",
         "14" : "tue",
         "15" : "wed",
         "16" : "thu",
         "17" : "fri",
         "2" : "thu",
         "20" : "mon",
         "21" : "tue",
         "22" : "wed",
         "23" : "thu",
         "24" : "fri",
         "27" : "mon",
         "28" : "tue",
         "29" : "wed",
         "3" : "fri",
         "30" : "thu",
         "31" : "fri",
         "6" : "mon",
         "7" : "tue",
         "8" : "wed",
         "9" : "thu"
      },
      "Jun" : {
         "1" : "mon",
         "10" : "wed",
         "11" : "thu",
         "12" : "fri",
         "15" : "mon",
         "16" : "tue",
         "17" : "wed",
         "18" : "thu",
         "19" : "fri",
         "2" : "tue",
         "22" : "mon",
         "23" : "tue",
         "24" : "wed",
         "25" : "thu",
         "26" : "fri",
         "29" : "mon",
         "3" : "wed",
         "30" : "tue",
         "4" : "thu",
         "5" : "fri",
         "8" : "mon",
         "9" : "tue"
      },
      "Mar" : {
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "21" : "sat",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "30" : "mon",
         "31" : "tue",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      },
      "May" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "29" : "fri",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri"
      },
      "Nov" : {
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "30" : "mon",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      },
      "Oct" : {
         "1" : "thu",
         "12" : "mon",
         "13" : "tue",
         "14" : "wed",
         "15" : "thu",
         "16" : "fri",
         "19" : "mon",
         "2" : "fri",
         "20" : "tue",
         "21" : "wed",
         "22" : "thu",
         "23" : "fri",
         "26" : "mon",
         "27" : "tue",
         "28" : "wed",
         "29" : "thu",
         "30" : "fri",
         "5" : "mon",
         "6" : "tue",
         "7" : "wed",
         "8" : "thu",
         "9" : "fri"
      },
      "Sep" : {
         "1" : "tue",
         "10" : "thu",
         "11" : "fri",
         "14" : "mon",
         "15" : "tue",
         "16" : "wed",
         "17" : "thu",
         "18" : "fri",
         "2" : "wed",
         "21" : "mon",
         "22" : "tue",
         "23" : "wed",
         "24" : "thu",
         "25" : "fri",
         "28" : "mon",
         "29" : "tue",
         "3" : "thu",
         "30" : "wed",
         "4" : "fri",
         "7" : "mon",
         "8" : "tue",
         "9" : "wed"
      }
   },
   "2016" : {
      "Apr" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "29" : "fri",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri"
      },
      "Aug" : {
         "1" : "mon",
         "10" : "wed",
         "11" : "thu",
         "12" : "fri",
         "15" : "mon",
         "16" : "tue",
         "17" : "wed",
         "18" : "thu",
         "19" : "fri",
         "2" : "tue",
         "22" : "mon",
         "23" : "tue",
         "24" : "wed",
         "25" : "thu",
         "26" : "fri",
         "29" : "mon",
         "3" : "wed",
         "30" : "tue",
         "31" : "wed",
         "4" : "thu",
         "5" : "fri",
         "8" : "mon",
         "9" : "tue"
      },
      "Dec" : {
         "1" : "thu",
         "12" : "mon",
         "13" : "tue",
         "14" : "wed",
         "15" : "thu",
         "16" : "fri",
         "19" : "mon",
         "2" : "fri",
         "20" : "tue",
         "21" : "wed",
         "22" : "thu",
         "23" : "fri",
         "26" : "mon",
         "27" : "tue",
         "28" : "wed",
         "29" : "thu",
         "30" : "fri",
         "5" : "mon",
         "6" : "tue",
         "7" : "wed",
         "8" : "thu",
         "9" : "fri"
      },
      "Feb" : {
         "1" : "mon",
         "10" : "wed",
         "11" : "thu",
         "12" : "fri",
         "15" : "mon",
         "16" : "tue",
         "17" : "wed",
         "18" : "thu",
         "19" : "fri",
         "2" : "tue",
         "22" : "mon",
         "23" : "tue",
         "24" : "wed",
         "25" : "thu",
         "26" : "fri",
         "29" : "mon",
         "3" : "wed",
         "4" : "thu",
         "5" : "fri",
         "8" : "mon",
         "9" : "tue"
      },
      "Jan" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "29" : "fri",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri"
      },
      "Jul" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "29" : "fri",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri"
      },
      "Jun" : {
         "1" : "wed",
         "10" : "fri",
         "13" : "mon",
         "14" : "tue",
         "15" : "wed",
         "16" : "thu",
         "17" : "fri",
         "2" : "thu",
         "20" : "mon",
         "21" : "tue",
         "22" : "wed",
         "23" : "thu",
         "24" : "fri",
         "27" : "mon",
         "28" : "tue",
         "29" : "wed",
         "3" : "fri",
         "30" : "thu",
         "6" : "mon",
         "7" : "tue",
         "8" : "wed",
         "9" : "thu"
      },
      "Mar" : {
         "1" : "tue",
         "10" : "thu",
         "11" : "fri",
         "14" : "mon",
         "15" : "tue",
         "16" : "wed",
         "17" : "thu",
         "18" : "fri",
         "2" : "wed",
         "21" : "mon",
         "22" : "tue",
         "23" : "wed",
         "24" : "thu",
         "25" : "fri",
         "27" : "sun",
         "28" : "mon",
         "29" : "tue",
         "3" : "thu",
         "30" : "wed",
         "31" : "thu",
         "4" : "fri",
         "7" : "mon",
         "8" : "tue",
         "9" : "wed"
      },
      "May" : {
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "30" : "mon",
         "31" : "tue",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      },
      "Nov" : {
         "1" : "tue",
         "10" : "thu",
         "11" : "fri",
         "14" : "mon",
         "15" : "tue",
         "16" : "wed",
         "17" : "thu",
         "18" : "fri",
         "2" : "wed",
         "21" : "mon",
         "22" : "tue",
         "23" : "wed",
         "24" : "thu",
         "25" : "fri",
         "28" : "mon",
         "29" : "tue",
         "3" : "thu",
         "30" : "wed",
         "4" : "fri",
         "7" : "mon",
         "8" : "tue",
         "9" : "wed"
      },
      "Oct" : {
         "10" : "mon",
         "11" : "tue",
         "12" : "wed",
         "13" : "thu",
         "14" : "fri",
         "17" : "mon",
         "18" : "tue",
         "19" : "wed",
         "20" : "thu",
         "21" : "fri",
         "24" : "mon",
         "25" : "tue",
         "26" : "wed",
         "27" : "thu",
         "28" : "fri",
         "3" : "mon",
         "31" : "mon",
         "4" : "tue",
         "5" : "wed",
         "6" : "thu",
         "7" : "fri"
      },
      "Sep" : {
         "1" : "thu",
         "12" : "mon",
         "13" : "tue",
         "14" : "wed",
         "15" : "thu",
         "16" : "fri",
         "19" : "mon",
         "2" : "fri",
         "20" : "tue",
         "21" : "wed",
         "22" : "thu",
         "23" : "fri",
         "24" : "sat",
         "26" : "mon",
         "27" : "tue",
         "28" : "wed",
         "29" : "thu",
         "30" : "fri",
         "5" : "mon",
         "6" : "tue",
         "7" : "wed",
         "8" : "thu",
         "9" : "fri"
      }
   },
   "2017" : {
      "Apr" : {
         "10" : "mon",
         "11" : "tue",
         "12" : "wed",
         "13" : "thu",
         "14" : "fri",
         "16" : "sun",
         "17" : "mon",
         "18" : "tue",
         "19" : "wed",
         "20" : "thu",
         "21" : "fri",
         "24" : "mon",
         "25" : "tue",
         "26" : "wed",
         "27" : "thu",
         "28" : "fri",
         "3" : "mon",
         "4" : "tue",
         "5" : "wed",
         "6" : "thu",
         "7" : "fri"
      },
      "Aug" : {
         "1" : "tue",
         "10" : "thu",
         "11" : "fri",
         "14" : "mon",
         "15" : "tue",
         "16" : "wed",
         "17" : "thu",
         "18" : "fri",
         "2" : "wed",
         "21" : "mon",
         "22" : "tue",
         "23" : "wed",
         "24" : "thu",
         "25" : "fri",
         "28" : "mon",
         "29" : "tue",
         "3" : "thu",
         "30" : "wed",
         "31" : "thu",
         "4" : "fri",
         "7" : "mon",
         "8" : "tue",
         "9" : "wed"
      },
      "Dec" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "16" : "sat",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "29" : "fri",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri"
      },
      "Feb" : {
         "1" : "wed",
         "10" : "fri",
         "13" : "mon",
         "14" : "tue",
         "15" : "wed",
         "16" : "thu",
         "17" : "fri",
         "2" : "thu",
         "20" : "mon",
         "21" : "tue",
         "22" : "wed",
         "23" : "thu",
         "24" : "fri",
         "27" : "mon",
         "28" : "tue",
         "3" : "fri",
         "6" : "mon",
         "7" : "tue",
         "8" : "wed",
         "9" : "thu"
      },
      "Jan" : {
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "30" : "mon",
         "31" : "tue",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      },
      "Jul" : {
         "10" : "mon",
         "11" : "tue",
         "12" : "wed",
         "13" : "thu",
         "14" : "fri",
         "17" : "mon",
         "18" : "tue",
         "19" : "wed",
         "20" : "thu",
         "21" : "fri",
         "24" : "mon",
         "25" : "tue",
         "26" : "wed",
         "27" : "thu",
         "28" : "fri",
         "3" : "mon",
         "31" : "mon",
         "4" : "tue",
         "5" : "wed",
         "6" : "thu",
         "7" : "fri"
      },
      "Jun" : {
         "1" : "thu",
         "12" : "mon",
         "13" : "tue",
         "14" : "wed",
         "15" : "thu",
         "16" : "fri",
         "19" : "mon",
         "2" : "fri",
         "20" : "tue",
         "21" : "wed",
         "22" : "thu",
         "23" : "fri",
         "26" : "mon",
         "27" : "tue",
         "28" : "wed",
         "29" : "thu",
         "30" : "fri",
         "5" : "mon",
         "6" : "tue",
         "7" : "wed",
         "8" : "thu",
         "9" : "fri"
      },
      "Mar" : {
         "1" : "wed",
         "10" : "fri",
         "13" : "mon",
         "14" : "tue",
         "15" : "wed",
         "16" : "thu",
         "17" : "fri",
         "2" : "thu",
         "20" : "mon",
         "21" : "tue",
         "22" : "wed",
         "23" : "thu",
         "24" : "fri",
         "27" : "mon",
         "28" : "tue",
         "29" : "wed",
         "3" : "fri",
         "30" : "thu",
         "31" : "fri",
         "6" : "mon",
         "7" : "tue",
         "8" : "wed",
         "9" : "thu"
      },
      "May" : {
         "1" : "mon",
         "10" : "wed",
         "11" : "thu",
         "12" : "fri",
         "15" : "mon",
         "16" : "tue",
         "17" : "wed",
         "18" : "thu",
         "19" : "fri",
         "2" : "tue",
         "22" : "mon",
         "23" : "tue",
         "24" : "wed",
         "25" : "thu",
         "26" : "fri",
         "29" : "mon",
         "3" : "wed",
         "30" : "tue",
         "31" : "wed",
         "4" : "thu",
         "5" : "fri",
         "8" : "mon",
         "9" : "tue"
      },
      "Nov" : {
         "1" : "wed",
         "10" : "fri",
         "13" : "mon",
         "14" : "tue",
         "15" : "wed",
         "16" : "thu",
         "17" : "fri",
         "2" : "thu",
         "20" : "mon",
         "21" : "tue",
         "22" : "wed",
         "23" : "thu",
         "24" : "fri",
         "27" : "mon",
         "28" : "tue",
         "29" : "wed",
         "3" : "fri",
         "30" : "thu",
         "6" : "mon",
         "7" : "tue",
         "8" : "wed",
         "9" : "thu"
      },
      "Oct" : {
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "30" : "mon",
         "31" : "tue",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      },
      "Sep" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "29" : "fri",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri"
      }
   },
   "2018" : {
      "Apr" : {
         "1" : "sun",
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "30" : "mon",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      },
      "Aug" : {
         "1" : "wed",
         "10" : "fri",
         "13" : "mon",
         "14" : "tue",
         "15" : "wed",
         "16" : "thu",
         "17" : "fri",
         "2" : "thu",
         "20" : "mon",
         "21" : "tue",
         "22" : "wed",
         "23" : "thu",
         "24" : "fri",
         "27" : "mon",
         "28" : "tue",
         "29" : "wed",
         "3" : "fri",
         "30" : "thu",
         "31" : "fri",
         "6" : "mon",
         "7" : "tue",
         "8" : "wed",
         "9" : "thu"
      },
      "Dec" : {
         "10" : "mon",
         "11" : "tue",
         "12" : "wed",
         "13" : "thu",
         "14" : "fri",
         "17" : "mon",
         "18" : "tue",
         "19" : "wed",
         "20" : "thu",
         "21" : "fri",
         "24" : "mon",
         "25" : "tue",
         "26" : "wed",
         "27" : "thu",
         "28" : "fri",
         "3" : "mon",
         "31" : "mon",
         "4" : "tue",
         "5" : "wed",
         "6" : "thu",
         "7" : "fri"
      },
      "Feb" : {
         "1" : "thu",
         "12" : "mon",
         "13" : "tue",
         "14" : "wed",
         "15" : "thu",
         "16" : "fri",
         "19" : "mon",
         "2" : "fri",
         "20" : "tue",
         "21" : "wed",
         "22" : "thu",
         "23" : "fri",
         "26" : "mon",
         "27" : "tue",
         "28" : "wed",
         "5" : "mon",
         "6" : "tue",
         "7" : "wed",
         "8" : "thu",
         "9" : "fri"
      },
      "Jan" : {
         "1" : "mon",
         "10" : "wed",
         "11" : "thu",
         "12" : "fri",
         "15" : "mon",
         "16" : "tue",
         "17" : "wed",
         "18" : "thu",
         "19" : "fri",
         "2" : "tue",
         "22" : "mon",
         "23" : "tue",
         "24" : "wed",
         "25" : "thu",
         "26" : "fri",
         "29" : "mon",
         "3" : "wed",
         "30" : "tue",
         "31" : "wed",
         "4" : "thu",
         "5" : "fri",
         "8" : "mon",
         "9" : "tue"
      },
      "Jul" : {
         "10" : "tue",
         "11" : "wed",
         "12" : "thu",
         "13" : "fri",
         "16" : "mon",
         "17" : "tue",
         "18" : "wed",
         "19" : "thu",
         "2" : "mon",
         "20" : "fri",
         "23" : "mon",
         "24" : "tue",
         "25" : "wed",
         "26" : "thu",
         "27" : "fri",
         "3" : "tue",
         "30" : "mon",
         "31" : "tue",
         "4" : "wed",
         "5" : "thu",
         "6" : "fri",
         "9" : "mon"
      },
      "Jun" : {
         "1" : "fri",
         "11" : "mon",
         "12" : "tue",
         "13" : "wed",
         "14" : "thu",
         "15" : "fri",
         "16" : "sat",
         "18" : "mon",
         "19" : "tue",
         "20" : "wed",
         "21" : "thu",
         "22" : "fri",
         "25" : "mon",
         "26" : "tue",
         "27" : "wed",
         "28" : "thu",
         "29" : "fri",
         "4" : "mon",
         "5" : "tue",
         "6" : "wed",
         "7" : "thu",
         "8" : "fri"
      },
      "Mar" : {
         "1" : "thu",
         "12" : "mon",
         "13" : "tue",
         "14" : "wed",
         "15" : "thu",
         "16" : "fri",
         "19" : "mon",
         "2" : "fri",
         "20" : "tue",
         "21" : "wed",
         "22" : "thu",
         "23" : "fri",
         "26" : "mon",
         "27" : "tue",
         "28" : "wed",
         "29" : "thu",
         "30" : "fri",
         "5" : "mon",
         "6" : "tue",
         "7" : "wed",
         "8" : "thu",
         "9" : "fri"
      },
      "May" : {
         "1" : "tue",
         "10" : "thu",
         "11" : "fri",
         "14" : "mon",
         "15" : "tue",
         "16" : "wed",
         "17" : "thu",
         "18" : "fri",
         "2" : "wed",
         "21" : "mon",
         "22" : "tue",
         "23" : "wed",
         "24" : "thu",
         "25" : "fri",
         "28" : "mon",
         "29" : "tue",
         "3" : "thu",
         "30" : "wed",
         "31" : "thu",
         "4" : "fri",
         "7" : "mon",
         "8" : "tue",
         "9" : "wed"
      },
      "Nov" : {
         "1" : "thu",
         "12" : "mon",
         "13" : "tue",
         "14" : "wed",
         "15" : "thu",
         "16" : "fri",
         "19" : "mon",
         "2" : "fri",
         "20" : "tue",
         "21" : "wed",
         "22" : "thu",
         "23" : "fri",
         "26" : "mon",
         "27" : "tue",
         "28" : "wed",
         "29" : "thu",
         "30" : "fri",
         "5" : "mon",
         "6" : "tue",
         "7" : "wed",
         "8" : "thu",
         "9" : "fri"
      },
      "Oct" : {
         "1" : "mon",
         "10" : "wed",
         "11" : "thu",
         "12" : "fri",
         "15" : "mon",
         "16" : "tue",
         "17" : "wed",
         "18" : "thu",
         "19" : "fri",
         "2" : "tue",
         "22" : "mon",
         "23" : "tue",
         "24" : "wed",
         "25" : "thu",
         "26" : "fri",
         "29" : "mon",
         "3" : "wed",
         "30" : "tue",
         "31" : "wed",
         "4" : "thu",
         "5" : "fri",
         "8" : "mon",
         "9" : "tue"
      },
      "Sep" : {
         "10" : "mon",
         "11" : "tue",
         "12" : "wed",
         "13" : "thu",
         "14" : "fri",
         "17" : "mon",
         "18" : "tue",
         "19" : "wed",
         "20" : "thu",
         "21" : "fri",
         "24" : "mon",
         "25" : "tue",
         "26" : "wed",
         "27" : "thu",
         "28" : "fri",
         "3" : "mon",
         "4" : "tue",
         "5" : "wed",
         "6" : "thu",
         "7" : "fri"
      }
   }
};

