var holidays = {
   "2013" : {
      "Apr" : {
         "1" : "Family Day",
         "27" : "Freedom Day"
      },
      "Aug" : {
         "9" : "National Women's Day"
      },
      "Dec" : {
         "16" : "Day of Reconciliation",
         "25" : "Christmas",
         "26" : "Day of Goodwill"
      },
      "Jan" : {
         "1" : "New Year's Day"
      },
      "Jun" : {
         "17" : "Youth Day (Soweto Day)"
      },
      "Mar" : {
         "21" : "Human Rights Day",
         "29" : "Good Friday",
         "31" : "Easter Sunday"
      },
      "May" : {
         "1" : "Workers Day"
      },
      "Sep" : {
         "24" : "Heritage Day"
      }
   },
   "2014" : {
      "Apr" : {
         "18" : "Good Friday",
         "20" : "Easter Sunday",
         "21" : "Family Day",
         "28" : "Freedom Day"
      },
      "Aug" : {
         "9" : "National Women's Day"
      },
      "Dec" : {
         "16" : "Day of Reconciliation",
         "25" : "Christmas",
         "26" : "Day of Goodwill"
      },
      "Jan" : {
         "1" : "New Year's Day"
      },
      "Jun" : {
         "16" : "Youth Day (Soweto Day)"
      },
      "Mar" : {
         "21" : "Human Rights Day"
      },
      "May" : {
         "1" : "Workers Day"
      },
      "Sep" : {
         "24" : "Heritage Day"
      }
   },
   "2015" : {
      "Apr" : {
         "27" : "Freedom Day",
         "3" : "Good Friday",
         "5" : "Easter Sunday",
         "6" : "Family Day"
      },
      "Aug" : {
         "10" : "National Women's Day"
      },
      "Dec" : {
         "16" : "Day of Reconciliation",
         "25" : "Christmas",
         "26" : "Day of Goodwill"
      },
      "Jan" : {
         "1" : "New Year's Day"
      },
      "Jun" : {
         "16" : "Youth Day (Soweto Day)"
      },
      "Mar" : {
         "21" : "Human Rights Day"
      },
      "May" : {
         "1" : "Workers Day"
      },
      "Sep" : {
         "24" : "Heritage Day"
      }
   },
   "2016" : {
      "Apr" : {
         "27" : "Freedom Day"
      },
      "Aug" : {
         "9" : "National Women's Day"
      },
      "Dec" : {
         "16" : "Day of Reconciliation",
         "26" : "Christmas"
      },
      "Jan" : {
         "1" : "New Year's Day"
      },
      "Jun" : {
         "16" : "Youth Day (Soweto Day)"
      },
      "Mar" : {
         "21" : "Human Rights Day",
         "25" : "Good Friday",
         "27" : "Easter Sunday",
         "28" : "Family Day"
      },
      "May" : {
         "2" : "Workers Day"
      },
      "Sep" : {
         "24" : "Heritage Day"
      }
   },
   "2017" : {
      "Apr" : {
         "14" : "Good Friday",
         "16" : "Easter Sunday",
         "17" : "Family Day",
         "27" : "Freedom Day"
      },
      "Aug" : {
         "9" : "National Women's Day"
      },
      "Dec" : {
         "16" : "Day of Reconciliation",
         "25" : "Christmas",
         "26" : "Day of Goodwill"
      },
      "Jan" : {
         "2" : "New Year's Day"
      },
      "Jun" : {
         "16" : "Youth Day (Soweto Day)"
      },
      "Mar" : {
         "21" : "Human Rights Day"
      },
      "May" : {
         "1" : "Workers Day"
      },
      "Sep" : {
         "25" : "Heritage Day"
      }
   },
   "2018" : {
      "Apr" : {
         "1" : "Easter Sunday",
         "2" : "Family Day",
         "27" : "Freedom Day"
      },
      "Aug" : {
         "9" : "National Women's Day"
      },
      "Dec" : {
         "17" : "Day of Reconciliation",
         "25" : "Christmas",
         "26" : "Day of Goodwill"
      },
      "Jan" : {
         "1" : "New Year's Day"
      },
      "Jun" : {
         "16" : "Youth Day (Soweto Day)"
      },
      "Mar" : {
         "21" : "Human Rights Day",
         "30" : "Good Friday"
      },
      "May" : {
         "1" : "Workers Day"
      },
      "Sep" : {
         "24" : "Heritage Day"
      }
   }
};

var workdays = {
   "2013" : {
      "Apr" : {
         "1" : "Mon",
         "10" : "Wed",
         "11" : "Thu",
         "12" : "Fri",
         "15" : "Mon",
         "16" : "Tue",
         "17" : "Wed",
         "18" : "Thu",
         "19" : "Fri",
         "2" : "Tue",
         "22" : "Mon",
         "23" : "Tue",
         "24" : "Wed",
         "25" : "Thu",
         "26" : "Fri",
         "27" : "Sat",
         "29" : "Mon",
         "3" : "Wed",
         "30" : "Tue",
         "4" : "Thu",
         "5" : "Fri",
         "8" : "Mon",
         "9" : "Tue"
      },
      "Aug" : {
         "1" : "Thu",
         "12" : "Mon",
         "13" : "Tue",
         "14" : "Wed",
         "15" : "Thu",
         "16" : "Fri",
         "19" : "Mon",
         "2" : "Fri",
         "20" : "Tue",
         "21" : "Wed",
         "22" : "Thu",
         "23" : "Fri",
         "26" : "Mon",
         "27" : "Tue",
         "28" : "Wed",
         "29" : "Thu",
         "30" : "Fri",
         "5" : "Mon",
         "6" : "Tue",
         "7" : "Wed",
         "8" : "Thu",
         "9" : "Fri"
      },
      "Dec" : {
         "10" : "Tue",
         "11" : "Wed",
         "12" : "Thu",
         "13" : "Fri",
         "16" : "Mon",
         "17" : "Tue",
         "18" : "Wed",
         "19" : "Thu",
         "2" : "Mon",
         "20" : "Fri",
         "23" : "Mon",
         "24" : "Tue",
         "25" : "Wed",
         "26" : "Thu",
         "27" : "Fri",
         "3" : "Tue",
         "30" : "Mon",
         "31" : "Tue",
         "4" : "Wed",
         "5" : "Thu",
         "6" : "Fri",
         "9" : "Mon"
      },
      "Feb" : {
         "1" : "Fri",
         "11" : "Mon",
         "12" : "Tue",
         "13" : "Wed",
         "14" : "Thu",
         "15" : "Fri",
         "18" : "Mon",
         "19" : "Tue",
         "20" : "Wed",
         "21" : "Thu",
         "22" : "Fri",
         "25" : "Mon",
         "26" : "Tue",
         "27" : "Wed",
         "28" : "Thu",
         "4" : "Mon",
         "5" : "Tue",
         "6" : "Wed",
         "7" : "Thu",
         "8" : "Fri"
      },
      "Jan" : {
         "1" : "Tue",
         "10" : "Thu",
         "11" : "Fri",
         "14" : "Mon",
         "15" : "Tue",
         "16" : "Wed",
         "17" : "Thu",
         "18" : "Fri",
         "2" : "Wed",
         "21" : "Mon",
         "22" : "Tue",
         "23" : "Wed",
         "24" : "Thu",
         "25" : "Fri",
         "28" : "Mon",
         "29" : "Tue",
         "3" : "Thu",
         "30" : "Wed",
         "31" : "Thu",
         "4" : "Fri",
         "7" : "Mon",
         "8" : "Tue",
         "9" : "Wed"
      },
      "Jul" : {
         "1" : "Mon",
         "10" : "Wed",
         "11" : "Thu",
         "12" : "Fri",
         "15" : "Mon",
         "16" : "Tue",
         "17" : "Wed",
         "18" : "Thu",
         "19" : "Fri",
         "2" : "Tue",
         "22" : "Mon",
         "23" : "Tue",
         "24" : "Wed",
         "25" : "Thu",
         "26" : "Fri",
         "29" : "Mon",
         "3" : "Wed",
         "30" : "Tue",
         "31" : "Wed",
         "4" : "Thu",
         "5" : "Fri",
         "8" : "Mon",
         "9" : "Tue"
      },
      "Jun" : {
         "10" : "Mon",
         "11" : "Tue",
         "12" : "Wed",
         "13" : "Thu",
         "14" : "Fri",
         "17" : "Mon",
         "18" : "Tue",
         "19" : "Wed",
         "20" : "Thu",
         "21" : "Fri",
         "24" : "Mon",
         "25" : "Tue",
         "26" : "Wed",
         "27" : "Thu",
         "28" : "Fri",
         "3" : "Mon",
         "4" : "Tue",
         "5" : "Wed",
         "6" : "Thu",
         "7" : "Fri"
      },
      "Mar" : {
         "1" : "Fri",
         "11" : "Mon",
         "12" : "Tue",
         "13" : "Wed",
         "14" : "Thu",
         "15" : "Fri",
         "18" : "Mon",
         "19" : "Tue",
         "20" : "Wed",
         "21" : "Thu",
         "22" : "Fri",
         "25" : "Mon",
         "26" : "Tue",
         "27" : "Wed",
         "28" : "Thu",
         "29" : "Fri",
         "31" : "Sun",
         "4" : "Mon",
         "5" : "Tue",
         "6" : "Wed",
         "7" : "Thu",
         "8" : "Fri"
      },
      "May" : {
         "1" : "Wed",
         "10" : "Fri",
         "13" : "Mon",
         "14" : "Tue",
         "15" : "Wed",
         "16" : "Thu",
         "17" : "Fri",
         "2" : "Thu",
         "20" : "Mon",
         "21" : "Tue",
         "22" : "Wed",
         "23" : "Thu",
         "24" : "Fri",
         "27" : "Mon",
         "28" : "Tue",
         "29" : "Wed",
         "3" : "Fri",
         "30" : "Thu",
         "31" : "Fri",
         "6" : "Mon",
         "7" : "Tue",
         "8" : "Wed",
         "9" : "Thu"
      },
      "Nov" : {
         "1" : "Fri",
         "11" : "Mon",
         "12" : "Tue",
         "13" : "Wed",
         "14" : "Thu",
         "15" : "Fri",
         "18" : "Mon",
         "19" : "Tue",
         "20" : "Wed",
         "21" : "Thu",
         "22" : "Fri",
         "25" : "Mon",
         "26" : "Tue",
         "27" : "Wed",
         "28" : "Thu",
         "29" : "Fri",
         "4" : "Mon",
         "5" : "Tue",
         "6" : "Wed",
         "7" : "Thu",
         "8" : "Fri"
      },
      "Oct" : {
         "1" : "Tue",
         "10" : "Thu",
         "11" : "Fri",
         "14" : "Mon",
         "15" : "Tue",
         "16" : "Wed",
         "17" : "Thu",
         "18" : "Fri",
         "2" : "Wed",
         "21" : "Mon",
         "22" : "Tue",
         "23" : "Wed",
         "24" : "Thu",
         "25" : "Fri",
         "28" : "Mon",
         "29" : "Tue",
         "3" : "Thu",
         "30" : "Wed",
         "31" : "Thu",
         "4" : "Fri",
         "7" : "Mon",
         "8" : "Tue",
         "9" : "Wed"
      },
      "Sep" : {
         "10" : "Tue",
         "11" : "Wed",
         "12" : "Thu",
         "13" : "Fri",
         "16" : "Mon",
         "17" : "Tue",
         "18" : "Wed",
         "19" : "Thu",
         "2" : "Mon",
         "20" : "Fri",
         "23" : "Mon",
         "24" : "Tue",
         "25" : "Wed",
         "26" : "Thu",
         "27" : "Fri",
         "3" : "Tue",
         "30" : "Mon",
         "4" : "Wed",
         "5" : "Thu",
         "6" : "Fri",
         "9" : "Mon"
      }
   },
   "2014" : {
      "Apr" : {
         "1" : "Tue",
         "10" : "Thu",
         "11" : "Fri",
         "14" : "Mon",
         "15" : "Tue",
         "16" : "Wed",
         "17" : "Thu",
         "18" : "Fri",
         "2" : "Wed",
         "20" : "Sun",
         "21" : "Mon",
         "22" : "Tue",
         "23" : "Wed",
         "24" : "Thu",
         "25" : "Fri",
         "28" : "Mon",
         "29" : "Tue",
         "3" : "Thu",
         "30" : "Wed",
         "4" : "Fri",
         "7" : "Mon",
         "8" : "Tue",
         "9" : "Wed"
      },
      "Aug" : {
         "1" : "Fri",
         "11" : "Mon",
         "12" : "Tue",
         "13" : "Wed",
         "14" : "Thu",
         "15" : "Fri",
         "18" : "Mon",
         "19" : "Tue",
         "20" : "Wed",
         "21" : "Thu",
         "22" : "Fri",
         "25" : "Mon",
         "26" : "Tue",
         "27" : "Wed",
         "28" : "Thu",
         "29" : "Fri",
         "4" : "Mon",
         "5" : "Tue",
         "6" : "Wed",
         "7" : "Thu",
         "8" : "Fri",
         "9" : "Sat"
      },
      "Dec" : {
         "1" : "Mon",
         "10" : "Wed",
         "11" : "Thu",
         "12" : "Fri",
         "15" : "Mon",
         "16" : "Tue",
         "17" : "Wed",
         "18" : "Thu",
         "19" : "Fri",
         "2" : "Tue",
         "22" : "Mon",
         "23" : "Tue",
         "24" : "Wed",
         "25" : "Thu",
         "26" : "Fri",
         "29" : "Mon",
         "3" : "Wed",
         "30" : "Tue",
         "31" : "Wed",
         "4" : "Thu",
         "5" : "Fri",
         "8" : "Mon",
         "9" : "Tue"
      },
      "Feb" : {
         "10" : "Mon",
         "11" : "Tue",
         "12" : "Wed",
         "13" : "Thu",
         "14" : "Fri",
         "17" : "Mon",
         "18" : "Tue",
         "19" : "Wed",
         "20" : "Thu",
         "21" : "Fri",
         "24" : "Mon",
         "25" : "Tue",
         "26" : "Wed",
         "27" : "Thu",
         "28" : "Fri",
         "3" : "Mon",
         "4" : "Tue",
         "5" : "Wed",
         "6" : "Thu",
         "7" : "Fri"
      },
      "Jan" : {
         "1" : "Wed",
         "10" : "Fri",
         "13" : "Mon",
         "14" : "Tue",
         "15" : "Wed",
         "16" : "Thu",
         "17" : "Fri",
         "2" : "Thu",
         "20" : "Mon",
         "21" : "Tue",
         "22" : "Wed",
         "23" : "Thu",
         "24" : "Fri",
         "27" : "Mon",
         "28" : "Tue",
         "29" : "Wed",
         "3" : "Fri",
         "30" : "Thu",
         "31" : "Fri",
         "6" : "Mon",
         "7" : "Tue",
         "8" : "Wed",
         "9" : "Thu"
      },
      "Jul" : {
         "1" : "Tue",
         "10" : "Thu",
         "11" : "Fri",
         "14" : "Mon",
         "15" : "Tue",
         "16" : "Wed",
         "17" : "Thu",
         "18" : "Fri",
         "2" : "Wed",
         "21" : "Mon",
         "22" : "Tue",
         "23" : "Wed",
         "24" : "Thu",
         "25" : "Fri",
         "28" : "Mon",
         "29" : "Tue",
         "3" : "Thu",
         "30" : "Wed",
         "31" : "Thu",
         "4" : "Fri",
         "7" : "Mon",
         "8" : "Tue",
         "9" : "Wed"
      },
      "Jun" : {
         "10" : "Tue",
         "11" : "Wed",
         "12" : "Thu",
         "13" : "Fri",
         "16" : "Mon",
         "17" : "Tue",
         "18" : "Wed",
         "19" : "Thu",
         "2" : "Mon",
         "20" : "Fri",
         "23" : "Mon",
         "24" : "Tue",
         "25" : "Wed",
         "26" : "Thu",
         "27" : "Fri",
         "3" : "Tue",
         "30" : "Mon",
         "4" : "Wed",
         "5" : "Thu",
         "6" : "Fri",
         "9" : "Mon"
      },
      "Mar" : {
         "10" : "Mon",
         "11" : "Tue",
         "12" : "Wed",
         "13" : "Thu",
         "14" : "Fri",
         "17" : "Mon",
         "18" : "Tue",
         "19" : "Wed",
         "20" : "Thu",
         "21" : "Fri",
         "24" : "Mon",
         "25" : "Tue",
         "26" : "Wed",
         "27" : "Thu",
         "28" : "Fri",
         "3" : "Mon",
         "31" : "Mon",
         "4" : "Tue",
         "5" : "Wed",
         "6" : "Thu",
         "7" : "Fri"
      },
      "May" : {
         "1" : "Thu",
         "12" : "Mon",
         "13" : "Tue",
         "14" : "Wed",
         "15" : "Thu",
         "16" : "Fri",
         "19" : "Mon",
         "2" : "Fri",
         "20" : "Tue",
         "21" : "Wed",
         "22" : "Thu",
         "23" : "Fri",
         "26" : "Mon",
         "27" : "Tue",
         "28" : "Wed",
         "29" : "Thu",
         "30" : "Fri",
         "5" : "Mon",
         "6" : "Tue",
         "7" : "Wed",
         "8" : "Thu",
         "9" : "Fri"
      },
      "Nov" : {
         "10" : "Mon",
         "11" : "Tue",
         "12" : "Wed",
         "13" : "Thu",
         "14" : "Fri",
         "17" : "Mon",
         "18" : "Tue",
         "19" : "Wed",
         "20" : "Thu",
         "21" : "Fri",
         "24" : "Mon",
         "25" : "Tue",
         "26" : "Wed",
         "27" : "Thu",
         "28" : "Fri",
         "3" : "Mon",
         "4" : "Tue",
         "5" : "Wed",
         "6" : "Thu",
         "7" : "Fri"
      },
      "Oct" : {
         "1" : "Wed",
         "10" : "Fri",
         "13" : "Mon",
         "14" : "Tue",
         "15" : "Wed",
         "16" : "Thu",
         "17" : "Fri",
         "2" : "Thu",
         "20" : "Mon",
         "21" : "Tue",
         "22" : "Wed",
         "23" : "Thu",
         "24" : "Fri",
         "27" : "Mon",
         "28" : "Tue",
         "29" : "Wed",
         "3" : "Fri",
         "30" : "Thu",
         "31" : "Fri",
         "6" : "Mon",
         "7" : "Tue",
         "8" : "Wed",
         "9" : "Thu"
      },
      "Sep" : {
         "1" : "Mon",
         "10" : "Wed",
         "11" : "Thu",
         "12" : "Fri",
         "15" : "Mon",
         "16" : "Tue",
         "17" : "Wed",
         "18" : "Thu",
         "19" : "Fri",
         "2" : "Tue",
         "22" : "Mon",
         "23" : "Tue",
         "24" : "Wed",
         "25" : "Thu",
         "26" : "Fri",
         "29" : "Mon",
         "3" : "Wed",
         "30" : "Tue",
         "4" : "Thu",
         "5" : "Fri",
         "8" : "Mon",
         "9" : "Tue"
      }
   },
   "2015" : {
      "Apr" : {
         "1" : "Wed",
         "10" : "Fri",
         "13" : "Mon",
         "14" : "Tue",
         "15" : "Wed",
         "16" : "Thu",
         "17" : "Fri",
         "2" : "Thu",
         "20" : "Mon",
         "21" : "Tue",
         "22" : "Wed",
         "23" : "Thu",
         "24" : "Fri",
         "27" : "Mon",
         "28" : "Tue",
         "29" : "Wed",
         "3" : "Fri",
         "30" : "Thu",
         "5" : "Sun",
         "6" : "Mon",
         "7" : "Tue",
         "8" : "Wed",
         "9" : "Thu"
      },
      "Aug" : {
         "10" : "Mon",
         "11" : "Tue",
         "12" : "Wed",
         "13" : "Thu",
         "14" : "Fri",
         "17" : "Mon",
         "18" : "Tue",
         "19" : "Wed",
         "20" : "Thu",
         "21" : "Fri",
         "24" : "Mon",
         "25" : "Tue",
         "26" : "Wed",
         "27" : "Thu",
         "28" : "Fri",
         "3" : "Mon",
         "31" : "Mon",
         "4" : "Tue",
         "5" : "Wed",
         "6" : "Thu",
         "7" : "Fri"
      },
      "Dec" : {
         "1" : "Tue",
         "10" : "Thu",
         "11" : "Fri",
         "14" : "Mon",
         "15" : "Tue",
         "16" : "Wed",
         "17" : "Thu",
         "18" : "Fri",
         "2" : "Wed",
         "21" : "Mon",
         "22" : "Tue",
         "23" : "Wed",
         "24" : "Thu",
         "25" : "Fri",
         "26" : "Sat",
         "28" : "Mon",
         "29" : "Tue",
         "3" : "Thu",
         "30" : "Wed",
         "31" : "Thu",
         "4" : "Fri",
         "7" : "Mon",
         "8" : "Tue",
         "9" : "Wed"
      },
      "Feb" : {
         "10" : "Tue",
         "11" : "Wed",
         "12" : "Thu",
         "13" : "Fri",
         "16" : "Mon",
         "17" : "Tue",
         "18" : "Wed",
         "19" : "Thu",
         "2" : "Mon",
         "20" : "Fri",
         "23" : "Mon",
         "24" : "Tue",
         "25" : "Wed",
         "26" : "Thu",
         "27" : "Fri",
         "3" : "Tue",
         "4" : "Wed",
         "5" : "Thu",
         "6" : "Fri",
         "9" : "Mon"
      },
      "Jan" : {
         "1" : "Thu",
         "12" : "Mon",
         "13" : "Tue",
         "14" : "Wed",
         "15" : "Thu",
         "16" : "Fri",
         "19" : "Mon",
         "2" : "Fri",
         "20" : "Tue",
         "21" : "Wed",
         "22" : "Thu",
         "23" : "Fri",
         "26" : "Mon",
         "27" : "Tue",
         "28" : "Wed",
         "29" : "Thu",
         "30" : "Fri",
         "5" : "Mon",
         "6" : "Tue",
         "7" : "Wed",
         "8" : "Thu",
         "9" : "Fri"
      },
      "Jul" : {
         "1" : "Wed",
         "10" : "Fri",
         "13" : "Mon",
         "14" : "Tue",
         "15" : "Wed",
         "16" : "Thu",
         "17" : "Fri",
         "2" : "Thu",
         "20" : "Mon",
         "21" : "Tue",
         "22" : "Wed",
         "23" : "Thu",
         "24" : "Fri",
         "27" : "Mon",
         "28" : "Tue",
         "29" : "Wed",
         "3" : "Fri",
         "30" : "Thu",
         "31" : "Fri",
         "6" : "Mon",
         "7" : "Tue",
         "8" : "Wed",
         "9" : "Thu"
      },
      "Jun" : {
         "1" : "Mon",
         "10" : "Wed",
         "11" : "Thu",
         "12" : "Fri",
         "15" : "Mon",
         "16" : "Tue",
         "17" : "Wed",
         "18" : "Thu",
         "19" : "Fri",
         "2" : "Tue",
         "22" : "Mon",
         "23" : "Tue",
         "24" : "Wed",
         "25" : "Thu",
         "26" : "Fri",
         "29" : "Mon",
         "3" : "Wed",
         "30" : "Tue",
         "4" : "Thu",
         "5" : "Fri",
         "8" : "Mon",
         "9" : "Tue"
      },
      "Mar" : {
         "10" : "Tue",
         "11" : "Wed",
         "12" : "Thu",
         "13" : "Fri",
         "16" : "Mon",
         "17" : "Tue",
         "18" : "Wed",
         "19" : "Thu",
         "2" : "Mon",
         "20" : "Fri",
         "21" : "Sat",
         "23" : "Mon",
         "24" : "Tue",
         "25" : "Wed",
         "26" : "Thu",
         "27" : "Fri",
         "3" : "Tue",
         "30" : "Mon",
         "31" : "Tue",
         "4" : "Wed",
         "5" : "Thu",
         "6" : "Fri",
         "9" : "Mon"
      },
      "May" : {
         "1" : "Fri",
         "11" : "Mon",
         "12" : "Tue",
         "13" : "Wed",
         "14" : "Thu",
         "15" : "Fri",
         "18" : "Mon",
         "19" : "Tue",
         "20" : "Wed",
         "21" : "Thu",
         "22" : "Fri",
         "25" : "Mon",
         "26" : "Tue",
         "27" : "Wed",
         "28" : "Thu",
         "29" : "Fri",
         "4" : "Mon",
         "5" : "Tue",
         "6" : "Wed",
         "7" : "Thu",
         "8" : "Fri"
      },
      "Nov" : {
         "10" : "Tue",
         "11" : "Wed",
         "12" : "Thu",
         "13" : "Fri",
         "16" : "Mon",
         "17" : "Tue",
         "18" : "Wed",
         "19" : "Thu",
         "2" : "Mon",
         "20" : "Fri",
         "23" : "Mon",
         "24" : "Tue",
         "25" : "Wed",
         "26" : "Thu",
         "27" : "Fri",
         "3" : "Tue",
         "30" : "Mon",
         "4" : "Wed",
         "5" : "Thu",
         "6" : "Fri",
         "9" : "Mon"
      },
      "Oct" : {
         "1" : "Thu",
         "12" : "Mon",
         "13" : "Tue",
         "14" : "Wed",
         "15" : "Thu",
         "16" : "Fri",
         "19" : "Mon",
         "2" : "Fri",
         "20" : "Tue",
         "21" : "Wed",
         "22" : "Thu",
         "23" : "Fri",
         "26" : "Mon",
         "27" : "Tue",
         "28" : "Wed",
         "29" : "Thu",
         "30" : "Fri",
         "5" : "Mon",
         "6" : "Tue",
         "7" : "Wed",
         "8" : "Thu",
         "9" : "Fri"
      },
      "Sep" : {
         "1" : "Tue",
         "10" : "Thu",
         "11" : "Fri",
         "14" : "Mon",
         "15" : "Tue",
         "16" : "Wed",
         "17" : "Thu",
         "18" : "Fri",
         "2" : "Wed",
         "21" : "Mon",
         "22" : "Tue",
         "23" : "Wed",
         "24" : "Thu",
         "25" : "Fri",
         "28" : "Mon",
         "29" : "Tue",
         "3" : "Thu",
         "30" : "Wed",
         "4" : "Fri",
         "7" : "Mon",
         "8" : "Tue",
         "9" : "Wed"
      }
   },
   "2016" : {
      "Apr" : {
         "1" : "Fri",
         "11" : "Mon",
         "12" : "Tue",
         "13" : "Wed",
         "14" : "Thu",
         "15" : "Fri",
         "18" : "Mon",
         "19" : "Tue",
         "20" : "Wed",
         "21" : "Thu",
         "22" : "Fri",
         "25" : "Mon",
         "26" : "Tue",
         "27" : "Wed",
         "28" : "Thu",
         "29" : "Fri",
         "4" : "Mon",
         "5" : "Tue",
         "6" : "Wed",
         "7" : "Thu",
         "8" : "Fri"
      },
      "Aug" : {
         "1" : "Mon",
         "10" : "Wed",
         "11" : "Thu",
         "12" : "Fri",
         "15" : "Mon",
         "16" : "Tue",
         "17" : "Wed",
         "18" : "Thu",
         "19" : "Fri",
         "2" : "Tue",
         "22" : "Mon",
         "23" : "Tue",
         "24" : "Wed",
         "25" : "Thu",
         "26" : "Fri",
         "29" : "Mon",
         "3" : "Wed",
         "30" : "Tue",
         "31" : "Wed",
         "4" : "Thu",
         "5" : "Fri",
         "8" : "Mon",
         "9" : "Tue"
      },
      "Dec" : {
         "1" : "Thu",
         "12" : "Mon",
         "13" : "Tue",
         "14" : "Wed",
         "15" : "Thu",
         "16" : "Fri",
         "19" : "Mon",
         "2" : "Fri",
         "20" : "Tue",
         "21" : "Wed",
         "22" : "Thu",
         "23" : "Fri",
         "26" : "Mon",
         "27" : "Tue",
         "28" : "Wed",
         "29" : "Thu",
         "30" : "Fri",
         "5" : "Mon",
         "6" : "Tue",
         "7" : "Wed",
         "8" : "Thu",
         "9" : "Fri"
      },
      "Feb" : {
         "1" : "Mon",
         "10" : "Wed",
         "11" : "Thu",
         "12" : "Fri",
         "15" : "Mon",
         "16" : "Tue",
         "17" : "Wed",
         "18" : "Thu",
         "19" : "Fri",
         "2" : "Tue",
         "22" : "Mon",
         "23" : "Tue",
         "24" : "Wed",
         "25" : "Thu",
         "26" : "Fri",
         "29" : "Mon",
         "3" : "Wed",
         "4" : "Thu",
         "5" : "Fri",
         "8" : "Mon",
         "9" : "Tue"
      },
      "Jan" : {
         "1" : "Fri",
         "11" : "Mon",
         "12" : "Tue",
         "13" : "Wed",
         "14" : "Thu",
         "15" : "Fri",
         "18" : "Mon",
         "19" : "Tue",
         "20" : "Wed",
         "21" : "Thu",
         "22" : "Fri",
         "25" : "Mon",
         "26" : "Tue",
         "27" : "Wed",
         "28" : "Thu",
         "29" : "Fri",
         "4" : "Mon",
         "5" : "Tue",
         "6" : "Wed",
         "7" : "Thu",
         "8" : "Fri"
      },
      "Jul" : {
         "1" : "Fri",
         "11" : "Mon",
         "12" : "Tue",
         "13" : "Wed",
         "14" : "Thu",
         "15" : "Fri",
         "18" : "Mon",
         "19" : "Tue",
         "20" : "Wed",
         "21" : "Thu",
         "22" : "Fri",
         "25" : "Mon",
         "26" : "Tue",
         "27" : "Wed",
         "28" : "Thu",
         "29" : "Fri",
         "4" : "Mon",
         "5" : "Tue",
         "6" : "Wed",
         "7" : "Thu",
         "8" : "Fri"
      },
      "Jun" : {
         "1" : "Wed",
         "10" : "Fri",
         "13" : "Mon",
         "14" : "Tue",
         "15" : "Wed",
         "16" : "Thu",
         "17" : "Fri",
         "2" : "Thu",
         "20" : "Mon",
         "21" : "Tue",
         "22" : "Wed",
         "23" : "Thu",
         "24" : "Fri",
         "27" : "Mon",
         "28" : "Tue",
         "29" : "Wed",
         "3" : "Fri",
         "30" : "Thu",
         "6" : "Mon",
         "7" : "Tue",
         "8" : "Wed",
         "9" : "Thu"
      },
      "Mar" : {
         "1" : "Tue",
         "10" : "Thu",
         "11" : "Fri",
         "14" : "Mon",
         "15" : "Tue",
         "16" : "Wed",
         "17" : "Thu",
         "18" : "Fri",
         "2" : "Wed",
         "21" : "Mon",
         "22" : "Tue",
         "23" : "Wed",
         "24" : "Thu",
         "25" : "Fri",
         "27" : "Sun",
         "28" : "Mon",
         "29" : "Tue",
         "3" : "Thu",
         "30" : "Wed",
         "31" : "Thu",
         "4" : "Fri",
         "7" : "Mon",
         "8" : "Tue",
         "9" : "Wed"
      },
      "May" : {
         "10" : "Tue",
         "11" : "Wed",
         "12" : "Thu",
         "13" : "Fri",
         "16" : "Mon",
         "17" : "Tue",
         "18" : "Wed",
         "19" : "Thu",
         "2" : "Mon",
         "20" : "Fri",
         "23" : "Mon",
         "24" : "Tue",
         "25" : "Wed",
         "26" : "Thu",
         "27" : "Fri",
         "3" : "Tue",
         "30" : "Mon",
         "31" : "Tue",
         "4" : "Wed",
         "5" : "Thu",
         "6" : "Fri",
         "9" : "Mon"
      },
      "Nov" : {
         "1" : "Tue",
         "10" : "Thu",
         "11" : "Fri",
         "14" : "Mon",
         "15" : "Tue",
         "16" : "Wed",
         "17" : "Thu",
         "18" : "Fri",
         "2" : "Wed",
         "21" : "Mon",
         "22" : "Tue",
         "23" : "Wed",
         "24" : "Thu",
         "25" : "Fri",
         "28" : "Mon",
         "29" : "Tue",
         "3" : "Thu",
         "30" : "Wed",
         "4" : "Fri",
         "7" : "Mon",
         "8" : "Tue",
         "9" : "Wed"
      },
      "Oct" : {
         "10" : "Mon",
         "11" : "Tue",
         "12" : "Wed",
         "13" : "Thu",
         "14" : "Fri",
         "17" : "Mon",
         "18" : "Tue",
         "19" : "Wed",
         "20" : "Thu",
         "21" : "Fri",
         "24" : "Mon",
         "25" : "Tue",
         "26" : "Wed",
         "27" : "Thu",
         "28" : "Fri",
         "3" : "Mon",
         "31" : "Mon",
         "4" : "Tue",
         "5" : "Wed",
         "6" : "Thu",
         "7" : "Fri"
      },
      "Sep" : {
         "1" : "Thu",
         "12" : "Mon",
         "13" : "Tue",
         "14" : "Wed",
         "15" : "Thu",
         "16" : "Fri",
         "19" : "Mon",
         "2" : "Fri",
         "20" : "Tue",
         "21" : "Wed",
         "22" : "Thu",
         "23" : "Fri",
         "24" : "Sat",
         "26" : "Mon",
         "27" : "Tue",
         "28" : "Wed",
         "29" : "Thu",
         "30" : "Fri",
         "5" : "Mon",
         "6" : "Tue",
         "7" : "Wed",
         "8" : "Thu",
         "9" : "Fri"
      }
   },
   "2017" : {
      "Apr" : {
         "10" : "Mon",
         "11" : "Tue",
         "12" : "Wed",
         "13" : "Thu",
         "14" : "Fri",
         "16" : "Sun",
         "17" : "Mon",
         "18" : "Tue",
         "19" : "Wed",
         "20" : "Thu",
         "21" : "Fri",
         "24" : "Mon",
         "25" : "Tue",
         "26" : "Wed",
         "27" : "Thu",
         "28" : "Fri",
         "3" : "Mon",
         "4" : "Tue",
         "5" : "Wed",
         "6" : "Thu",
         "7" : "Fri"
      },
      "Aug" : {
         "1" : "Tue",
         "10" : "Thu",
         "11" : "Fri",
         "14" : "Mon",
         "15" : "Tue",
         "16" : "Wed",
         "17" : "Thu",
         "18" : "Fri",
         "2" : "Wed",
         "21" : "Mon",
         "22" : "Tue",
         "23" : "Wed",
         "24" : "Thu",
         "25" : "Fri",
         "28" : "Mon",
         "29" : "Tue",
         "3" : "Thu",
         "30" : "Wed",
         "31" : "Thu",
         "4" : "Fri",
         "7" : "Mon",
         "8" : "Tue",
         "9" : "Wed"
      },
      "Dec" : {
         "1" : "Fri",
         "11" : "Mon",
         "12" : "Tue",
         "13" : "Wed",
         "14" : "Thu",
         "15" : "Fri",
         "16" : "Sat",
         "18" : "Mon",
         "19" : "Tue",
         "20" : "Wed",
         "21" : "Thu",
         "22" : "Fri",
         "25" : "Mon",
         "26" : "Tue",
         "27" : "Wed",
         "28" : "Thu",
         "29" : "Fri",
         "4" : "Mon",
         "5" : "Tue",
         "6" : "Wed",
         "7" : "Thu",
         "8" : "Fri"
      },
      "Feb" : {
         "1" : "Wed",
         "10" : "Fri",
         "13" : "Mon",
         "14" : "Tue",
         "15" : "Wed",
         "16" : "Thu",
         "17" : "Fri",
         "2" : "Thu",
         "20" : "Mon",
         "21" : "Tue",
         "22" : "Wed",
         "23" : "Thu",
         "24" : "Fri",
         "27" : "Mon",
         "28" : "Tue",
         "3" : "Fri",
         "6" : "Mon",
         "7" : "Tue",
         "8" : "Wed",
         "9" : "Thu"
      },
      "Jan" : {
         "10" : "Tue",
         "11" : "Wed",
         "12" : "Thu",
         "13" : "Fri",
         "16" : "Mon",
         "17" : "Tue",
         "18" : "Wed",
         "19" : "Thu",
         "2" : "Mon",
         "20" : "Fri",
         "23" : "Mon",
         "24" : "Tue",
         "25" : "Wed",
         "26" : "Thu",
         "27" : "Fri",
         "3" : "Tue",
         "30" : "Mon",
         "31" : "Tue",
         "4" : "Wed",
         "5" : "Thu",
         "6" : "Fri",
         "9" : "Mon"
      },
      "Jul" : {
         "10" : "Mon",
         "11" : "Tue",
         "12" : "Wed",
         "13" : "Thu",
         "14" : "Fri",
         "17" : "Mon",
         "18" : "Tue",
         "19" : "Wed",
         "20" : "Thu",
         "21" : "Fri",
         "24" : "Mon",
         "25" : "Tue",
         "26" : "Wed",
         "27" : "Thu",
         "28" : "Fri",
         "3" : "Mon",
         "31" : "Mon",
         "4" : "Tue",
         "5" : "Wed",
         "6" : "Thu",
         "7" : "Fri"
      },
      "Jun" : {
         "1" : "Thu",
         "12" : "Mon",
         "13" : "Tue",
         "14" : "Wed",
         "15" : "Thu",
         "16" : "Fri",
         "19" : "Mon",
         "2" : "Fri",
         "20" : "Tue",
         "21" : "Wed",
         "22" : "Thu",
         "23" : "Fri",
         "26" : "Mon",
         "27" : "Tue",
         "28" : "Wed",
         "29" : "Thu",
         "30" : "Fri",
         "5" : "Mon",
         "6" : "Tue",
         "7" : "Wed",
         "8" : "Thu",
         "9" : "Fri"
      },
      "Mar" : {
         "1" : "Wed",
         "10" : "Fri",
         "13" : "Mon",
         "14" : "Tue",
         "15" : "Wed",
         "16" : "Thu",
         "17" : "Fri",
         "2" : "Thu",
         "20" : "Mon",
         "21" : "Tue",
         "22" : "Wed",
         "23" : "Thu",
         "24" : "Fri",
         "27" : "Mon",
         "28" : "Tue",
         "29" : "Wed",
         "3" : "Fri",
         "30" : "Thu",
         "31" : "Fri",
         "6" : "Mon",
         "7" : "Tue",
         "8" : "Wed",
         "9" : "Thu"
      },
      "May" : {
         "1" : "Mon",
         "10" : "Wed",
         "11" : "Thu",
         "12" : "Fri",
         "15" : "Mon",
         "16" : "Tue",
         "17" : "Wed",
         "18" : "Thu",
         "19" : "Fri",
         "2" : "Tue",
         "22" : "Mon",
         "23" : "Tue",
         "24" : "Wed",
         "25" : "Thu",
         "26" : "Fri",
         "29" : "Mon",
         "3" : "Wed",
         "30" : "Tue",
         "31" : "Wed",
         "4" : "Thu",
         "5" : "Fri",
         "8" : "Mon",
         "9" : "Tue"
      },
      "Nov" : {
         "1" : "Wed",
         "10" : "Fri",
         "13" : "Mon",
         "14" : "Tue",
         "15" : "Wed",
         "16" : "Thu",
         "17" : "Fri",
         "2" : "Thu",
         "20" : "Mon",
         "21" : "Tue",
         "22" : "Wed",
         "23" : "Thu",
         "24" : "Fri",
         "27" : "Mon",
         "28" : "Tue",
         "29" : "Wed",
         "3" : "Fri",
         "30" : "Thu",
         "6" : "Mon",
         "7" : "Tue",
         "8" : "Wed",
         "9" : "Thu"
      },
      "Oct" : {
         "10" : "Tue",
         "11" : "Wed",
         "12" : "Thu",
         "13" : "Fri",
         "16" : "Mon",
         "17" : "Tue",
         "18" : "Wed",
         "19" : "Thu",
         "2" : "Mon",
         "20" : "Fri",
         "23" : "Mon",
         "24" : "Tue",
         "25" : "Wed",
         "26" : "Thu",
         "27" : "Fri",
         "3" : "Tue",
         "30" : "Mon",
         "31" : "Tue",
         "4" : "Wed",
         "5" : "Thu",
         "6" : "Fri",
         "9" : "Mon"
      },
      "Sep" : {
         "1" : "Fri",
         "11" : "Mon",
         "12" : "Tue",
         "13" : "Wed",
         "14" : "Thu",
         "15" : "Fri",
         "18" : "Mon",
         "19" : "Tue",
         "20" : "Wed",
         "21" : "Thu",
         "22" : "Fri",
         "25" : "Mon",
         "26" : "Tue",
         "27" : "Wed",
         "28" : "Thu",
         "29" : "Fri",
         "4" : "Mon",
         "5" : "Tue",
         "6" : "Wed",
         "7" : "Thu",
         "8" : "Fri"
      }
   },
   "2018" : {
      "Apr" : {
         "1" : "Sun",
         "10" : "Tue",
         "11" : "Wed",
         "12" : "Thu",
         "13" : "Fri",
         "16" : "Mon",
         "17" : "Tue",
         "18" : "Wed",
         "19" : "Thu",
         "2" : "Mon",
         "20" : "Fri",
         "23" : "Mon",
         "24" : "Tue",
         "25" : "Wed",
         "26" : "Thu",
         "27" : "Fri",
         "3" : "Tue",
         "30" : "Mon",
         "4" : "Wed",
         "5" : "Thu",
         "6" : "Fri",
         "9" : "Mon"
      },
      "Aug" : {
         "1" : "Wed",
         "10" : "Fri",
         "13" : "Mon",
         "14" : "Tue",
         "15" : "Wed",
         "16" : "Thu",
         "17" : "Fri",
         "2" : "Thu",
         "20" : "Mon",
         "21" : "Tue",
         "22" : "Wed",
         "23" : "Thu",
         "24" : "Fri",
         "27" : "Mon",
         "28" : "Tue",
         "29" : "Wed",
         "3" : "Fri",
         "30" : "Thu",
         "31" : "Fri",
         "6" : "Mon",
         "7" : "Tue",
         "8" : "Wed",
         "9" : "Thu"
      },
      "Dec" : {
         "10" : "Mon",
         "11" : "Tue",
         "12" : "Wed",
         "13" : "Thu",
         "14" : "Fri",
         "17" : "Mon",
         "18" : "Tue",
         "19" : "Wed",
         "20" : "Thu",
         "21" : "Fri",
         "24" : "Mon",
         "25" : "Tue",
         "26" : "Wed",
         "27" : "Thu",
         "28" : "Fri",
         "3" : "Mon",
         "31" : "Mon",
         "4" : "Tue",
         "5" : "Wed",
         "6" : "Thu",
         "7" : "Fri"
      },
      "Feb" : {
         "1" : "Thu",
         "12" : "Mon",
         "13" : "Tue",
         "14" : "Wed",
         "15" : "Thu",
         "16" : "Fri",
         "19" : "Mon",
         "2" : "Fri",
         "20" : "Tue",
         "21" : "Wed",
         "22" : "Thu",
         "23" : "Fri",
         "26" : "Mon",
         "27" : "Tue",
         "28" : "Wed",
         "5" : "Mon",
         "6" : "Tue",
         "7" : "Wed",
         "8" : "Thu",
         "9" : "Fri"
      },
      "Jan" : {
         "1" : "Mon",
         "10" : "Wed",
         "11" : "Thu",
         "12" : "Fri",
         "15" : "Mon",
         "16" : "Tue",
         "17" : "Wed",
         "18" : "Thu",
         "19" : "Fri",
         "2" : "Tue",
         "22" : "Mon",
         "23" : "Tue",
         "24" : "Wed",
         "25" : "Thu",
         "26" : "Fri",
         "29" : "Mon",
         "3" : "Wed",
         "30" : "Tue",
         "31" : "Wed",
         "4" : "Thu",
         "5" : "Fri",
         "8" : "Mon",
         "9" : "Tue"
      },
      "Jul" : {
         "10" : "Tue",
         "11" : "Wed",
         "12" : "Thu",
         "13" : "Fri",
         "16" : "Mon",
         "17" : "Tue",
         "18" : "Wed",
         "19" : "Thu",
         "2" : "Mon",
         "20" : "Fri",
         "23" : "Mon",
         "24" : "Tue",
         "25" : "Wed",
         "26" : "Thu",
         "27" : "Fri",
         "3" : "Tue",
         "30" : "Mon",
         "31" : "Tue",
         "4" : "Wed",
         "5" : "Thu",
         "6" : "Fri",
         "9" : "Mon"
      },
      "Jun" : {
         "1" : "Fri",
         "11" : "Mon",
         "12" : "Tue",
         "13" : "Wed",
         "14" : "Thu",
         "15" : "Fri",
         "16" : "Sat",
         "18" : "Mon",
         "19" : "Tue",
         "20" : "Wed",
         "21" : "Thu",
         "22" : "Fri",
         "25" : "Mon",
         "26" : "Tue",
         "27" : "Wed",
         "28" : "Thu",
         "29" : "Fri",
         "4" : "Mon",
         "5" : "Tue",
         "6" : "Wed",
         "7" : "Thu",
         "8" : "Fri"
      },
      "Mar" : {
         "1" : "Thu",
         "12" : "Mon",
         "13" : "Tue",
         "14" : "Wed",
         "15" : "Thu",
         "16" : "Fri",
         "19" : "Mon",
         "2" : "Fri",
         "20" : "Tue",
         "21" : "Wed",
         "22" : "Thu",
         "23" : "Fri",
         "26" : "Mon",
         "27" : "Tue",
         "28" : "Wed",
         "29" : "Thu",
         "30" : "Fri",
         "5" : "Mon",
         "6" : "Tue",
         "7" : "Wed",
         "8" : "Thu",
         "9" : "Fri"
      },
      "May" : {
         "1" : "Tue",
         "10" : "Thu",
         "11" : "Fri",
         "14" : "Mon",
         "15" : "Tue",
         "16" : "Wed",
         "17" : "Thu",
         "18" : "Fri",
         "2" : "Wed",
         "21" : "Mon",
         "22" : "Tue",
         "23" : "Wed",
         "24" : "Thu",
         "25" : "Fri",
         "28" : "Mon",
         "29" : "Tue",
         "3" : "Thu",
         "30" : "Wed",
         "31" : "Thu",
         "4" : "Fri",
         "7" : "Mon",
         "8" : "Tue",
         "9" : "Wed"
      },
      "Nov" : {
         "1" : "Thu",
         "12" : "Mon",
         "13" : "Tue",
         "14" : "Wed",
         "15" : "Thu",
         "16" : "Fri",
         "19" : "Mon",
         "2" : "Fri",
         "20" : "Tue",
         "21" : "Wed",
         "22" : "Thu",
         "23" : "Fri",
         "26" : "Mon",
         "27" : "Tue",
         "28" : "Wed",
         "29" : "Thu",
         "30" : "Fri",
         "5" : "Mon",
         "6" : "Tue",
         "7" : "Wed",
         "8" : "Thu",
         "9" : "Fri"
      },
      "Oct" : {
         "1" : "Mon",
         "10" : "Wed",
         "11" : "Thu",
         "12" : "Fri",
         "15" : "Mon",
         "16" : "Tue",
         "17" : "Wed",
         "18" : "Thu",
         "19" : "Fri",
         "2" : "Tue",
         "22" : "Mon",
         "23" : "Tue",
         "24" : "Wed",
         "25" : "Thu",
         "26" : "Fri",
         "29" : "Mon",
         "3" : "Wed",
         "30" : "Tue",
         "31" : "Wed",
         "4" : "Thu",
         "5" : "Fri",
         "8" : "Mon",
         "9" : "Tue"
      },
      "Sep" : {
         "10" : "Mon",
         "11" : "Tue",
         "12" : "Wed",
         "13" : "Thu",
         "14" : "Fri",
         "17" : "Mon",
         "18" : "Tue",
         "19" : "Wed",
         "20" : "Thu",
         "21" : "Fri",
         "24" : "Mon",
         "25" : "Tue",
         "26" : "Wed",
         "27" : "Thu",
         "28" : "Fri",
         "3" : "Mon",
         "4" : "Tue",
         "5" : "Wed",
         "6" : "Thu",
         "7" : "Fri"
      }
   }
};

var months = {
   "Apr" : "April",
   "Aug" : "August",
   "Dec" : "December",
   "Feb" : "February",
   "Jan" : "January",
   "Jul" : "July",
   "Jun" : "June",
   "Mar" : "March",
   "May" : "May",
   "Nov" : "November",
   "Oct" : "October",
   "Sep" : "September"
};

var month_num = {
   "0" : "Jan",
   "1" : "Feb",
   "10" : "Nov",
   "11" : "Dec",
   "2" : "Mar",
   "3" : "Apr",
   "4" : "May",
   "5" : "Jun",
   "6" : "Jul",
   "7" : "Aug",
   "8" : "Sep",
   "9" : "Oct"
};

